package com.xinshan.dao;

import com.xinshan.model.ActivityDetail;
import java.util.List;

public interface ActivityDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer activity_detail_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_detail
     *
     * @mbggenerated
     */
    int insert(ActivityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_detail
     *
     * @mbggenerated
     */
    ActivityDetail selectByPrimaryKey(Integer activity_detail_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_detail
     *
     * @mbggenerated
     */
    List<ActivityDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityDetail record);
}