package com.xinshan.dao;

import com.xinshan.model.ActivityValueAdded;
import java.util.List;

public interface ActivityValueAddedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_value_added
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer activity_value_added_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_value_added
     *
     * @mbggenerated
     */
    int insert(ActivityValueAdded record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_value_added
     *
     * @mbggenerated
     */
    ActivityValueAdded selectByPrimaryKey(Integer activity_value_added_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_value_added
     *
     * @mbggenerated
     */
    List<ActivityValueAdded> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_value_added
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityValueAdded record);
}