package com.xinshan.dao;

import com.xinshan.model.ActivityCommodity;
import java.util.List;

public interface ActivityCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer activity_commodity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_commodity
     *
     * @mbggenerated
     */
    int insert(ActivityCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_commodity
     *
     * @mbggenerated
     */
    ActivityCommodity selectByPrimaryKey(Integer activity_commodity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_commodity
     *
     * @mbggenerated
     */
    List<ActivityCommodity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityCommodity record);
}