package com.xinshan.dao;

import com.xinshan.model.BrandBoost;
import java.util.List;

public interface BrandBoostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_boost
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer brand_boost_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_boost
     *
     * @mbggenerated
     */
    int insert(BrandBoost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_boost
     *
     * @mbggenerated
     */
    BrandBoost selectByPrimaryKey(Integer brand_boost_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_boost
     *
     * @mbggenerated
     */
    List<BrandBoost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_boost
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BrandBoost record);
}