package com.xinshan.dao;

import com.xinshan.model.CashBackCommodity;
import java.util.List;

public interface CashBackCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_back_commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cash_back_commodity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_back_commodity
     *
     * @mbggenerated
     */
    int insert(CashBackCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_back_commodity
     *
     * @mbggenerated
     */
    CashBackCommodity selectByPrimaryKey(Integer cash_back_commodity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_back_commodity
     *
     * @mbggenerated
     */
    List<CashBackCommodity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_back_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CashBackCommodity record);
}