package com.xinshan.dao;

import com.xinshan.model.CategoryAttribute;
import java.util.List;

public interface CategoryAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer category_attribute_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_attribute
     *
     * @mbggenerated
     */
    int insert(CategoryAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_attribute
     *
     * @mbggenerated
     */
    CategoryAttribute selectByPrimaryKey(Integer category_attribute_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_attribute
     *
     * @mbggenerated
     */
    List<CategoryAttribute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CategoryAttribute record);
}