package com.xinshan.dao;

import com.xinshan.model.Checking;
import java.util.List;

public interface CheckingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer checking_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking
     *
     * @mbggenerated
     */
    int insert(Checking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking
     *
     * @mbggenerated
     */
    Checking selectByPrimaryKey(Integer checking_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking
     *
     * @mbggenerated
     */
    List<Checking> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Checking record);
}