package com.xinshan.dao;

import com.xinshan.model.CommoditySampleFixDetail;
import java.util.List;

public interface CommoditySampleFixDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_fix_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commodity_sample_fix_detail_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_fix_detail
     *
     * @mbggenerated
     */
    int insert(CommoditySampleFixDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_fix_detail
     *
     * @mbggenerated
     */
    CommoditySampleFixDetail selectByPrimaryKey(Integer commodity_sample_fix_detail_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_fix_detail
     *
     * @mbggenerated
     */
    List<CommoditySampleFixDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_fix_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommoditySampleFixDetail record);
}