package com.xinshan.dao;

import com.xinshan.model.CommodityPriceRecord;
import java.util.List;

public interface CommodityPriceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commodity_price_record_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_record
     *
     * @mbggenerated
     */
    int insert(CommodityPriceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_record
     *
     * @mbggenerated
     */
    CommodityPriceRecord selectByPrimaryKey(Integer commodity_price_record_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_record
     *
     * @mbggenerated
     */
    List<CommodityPriceRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityPriceRecord record);
}