package com.xinshan.dao;

import com.xinshan.model.CommodityPriceAdjust;
import java.util.List;

public interface CommodityPriceAdjustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_adjust
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commodity_price_adjust_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_adjust
     *
     * @mbggenerated
     */
    int insert(CommodityPriceAdjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_adjust
     *
     * @mbggenerated
     */
    CommodityPriceAdjust selectByPrimaryKey(Integer commodity_price_adjust_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_adjust
     *
     * @mbggenerated
     */
    List<CommodityPriceAdjust> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_price_adjust
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityPriceAdjust record);
}