package com.xinshan.dao;

import com.xinshan.model.CommoditySampleOutDetail;
import java.util.List;

public interface CommoditySampleOutDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_out_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commodity_sample_out_detail_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_out_detail
     *
     * @mbggenerated
     */
    int insert(CommoditySampleOutDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_out_detail
     *
     * @mbggenerated
     */
    CommoditySampleOutDetail selectByPrimaryKey(Integer commodity_sample_out_detail_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_out_detail
     *
     * @mbggenerated
     */
    List<CommoditySampleOutDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_sample_out_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommoditySampleOutDetail record);
}