package com.xinshan.dao;

import com.xinshan.model.GiftReturnCommodity;
import java.util.List;

public interface GiftReturnCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return_commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gift_return_commodity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return_commodity
     *
     * @mbggenerated
     */
    int insert(GiftReturnCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return_commodity
     *
     * @mbggenerated
     */
    GiftReturnCommodity selectByPrimaryKey(Integer gift_return_commodity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return_commodity
     *
     * @mbggenerated
     */
    List<GiftReturnCommodity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GiftReturnCommodity record);
}