package com.xinshan.dao;

import com.xinshan.model.GiftCommodity;
import java.util.List;

public interface GiftCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gift_commodity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_commodity
     *
     * @mbggenerated
     */
    int insert(GiftCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_commodity
     *
     * @mbggenerated
     */
    GiftCommodity selectByPrimaryKey(Integer gift_commodity_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_commodity
     *
     * @mbggenerated
     */
    List<GiftCommodity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GiftCommodity record);
}