package com.xinshan.dao;

import com.xinshan.model.GiftReturn;
import java.util.List;

public interface GiftReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gift_return_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return
     *
     * @mbggenerated
     */
    int insert(GiftReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return
     *
     * @mbggenerated
     */
    GiftReturn selectByPrimaryKey(Integer gift_return_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return
     *
     * @mbggenerated
     */
    List<GiftReturn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_return
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GiftReturn record);
}