package com.xinshan.dao;

import com.xinshan.model.InventoryOut;
import java.util.List;

public interface InventoryOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer inventory_out_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbggenerated
     */
    int insert(InventoryOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbggenerated
     */
    InventoryOut selectByPrimaryKey(Integer inventory_out_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbggenerated
     */
    List<InventoryOut> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InventoryOut record);
}