package com.xinshan.dao;

import com.xinshan.model.InventoryCarryOver;
import java.util.List;

public interface InventoryCarryOverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_carry_over
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer inventory_carry_over_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_carry_over
     *
     * @mbggenerated
     */
    int insert(InventoryCarryOver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_carry_over
     *
     * @mbggenerated
     */
    InventoryCarryOver selectByPrimaryKey(Integer inventory_carry_over_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_carry_over
     *
     * @mbggenerated
     */
    List<InventoryCarryOver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_carry_over
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InventoryCarryOver record);
}