package com.xinshan.dao;

import com.xinshan.model.Inventory;
import java.util.List;

public interface InventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer inventory_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    int insert(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    Inventory selectByPrimaryKey(Integer inventory_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    List<Inventory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Inventory record);
}