package com.xinshan.dao;

import com.xinshan.model.OrderClause;
import java.util.List;

public interface OrderClauseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_clause
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer order_clause_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_clause
     *
     * @mbggenerated
     */
    int insert(OrderClause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_clause
     *
     * @mbggenerated
     */
    OrderClause selectByPrimaryKey(Integer order_clause_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_clause
     *
     * @mbggenerated
     */
    List<OrderClause> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_clause
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderClause record);
}