package com.xinshan.dao;

import com.xinshan.model.OrderCommodityValueAddedCard;
import java.util.List;

public interface OrderCommodityValueAddedCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_commodity_value_added_card
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer order_commodity_value_added_card_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_commodity_value_added_card
     *
     * @mbggenerated
     */
    int insert(OrderCommodityValueAddedCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_commodity_value_added_card
     *
     * @mbggenerated
     */
    OrderCommodityValueAddedCard selectByPrimaryKey(Integer order_commodity_value_added_card_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_commodity_value_added_card
     *
     * @mbggenerated
     */
    List<OrderCommodityValueAddedCard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_commodity_value_added_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderCommodityValueAddedCard record);
}