package com.xinshan.dao;

import com.xinshan.model.Purchase;
import java.util.List;

public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer purchase_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int insert(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    Purchase selectByPrimaryKey(Integer purchase_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    List<Purchase> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Purchase record);
}