package com.xinshan.dao;

import com.xinshan.model.SalesTargetAnalysis;
import java.util.List;

public interface SalesTargetAnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_target_analysis
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sales_target_analysis_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_target_analysis
     *
     * @mbggenerated
     */
    int insert(SalesTargetAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_target_analysis
     *
     * @mbggenerated
     */
    SalesTargetAnalysis selectByPrimaryKey(Integer sales_target_analysis_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_target_analysis
     *
     * @mbggenerated
     */
    List<SalesTargetAnalysis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_target_analysis
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SalesTargetAnalysis record);
}