package com.xinshan.dao;

import com.xinshan.model.Settlement;
import java.util.List;

public interface SettlementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer settlement_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbggenerated
     */
    int insert(Settlement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbggenerated
     */
    Settlement selectByPrimaryKey(Integer settlement_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbggenerated
     */
    List<Settlement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Settlement record);
}