package com.xinshan.dao;

import com.xinshan.model.SpecialRightSell;
import java.util.List;

public interface SpecialRightSellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_right_sell
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer special_right_sell_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_right_sell
     *
     * @mbggenerated
     */
    int insert(SpecialRightSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_right_sell
     *
     * @mbggenerated
     */
    SpecialRightSell selectByPrimaryKey(Integer special_right_sell_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_right_sell
     *
     * @mbggenerated
     */
    List<SpecialRightSell> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_right_sell
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecialRightSell record);
}