package com.xinshan.dao;

import com.xinshan.model.SupplierSeries;
import java.util.List;

public interface SupplierSeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_series
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer supplier_series_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_series
     *
     * @mbggenerated
     */
    int insert(SupplierSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_series
     *
     * @mbggenerated
     */
    SupplierSeries selectByPrimaryKey(Integer supplier_series_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_series
     *
     * @mbggenerated
     */
    List<SupplierSeries> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_series
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SupplierSeries record);
}