package com.xinshan.dao;

import com.xinshan.model.UserBringUpCashBack;
import java.util.List;

public interface UserBringUpCashBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bring_up_cash_back
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bring_up_cash_back_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bring_up_cash_back
     *
     * @mbggenerated
     */
    int insert(UserBringUpCashBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bring_up_cash_back
     *
     * @mbggenerated
     */
    UserBringUpCashBack selectByPrimaryKey(Integer bring_up_cash_back_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bring_up_cash_back
     *
     * @mbggenerated
     */
    List<UserBringUpCashBack> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bring_up_cash_back
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBringUpCashBack record);
}