package com.xinshan.dao;

import com.xinshan.model.UserOpenid;
import java.util.List;

public interface UserOpenidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_openid
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer user_openid_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_openid
     *
     * @mbggenerated
     */
    int insert(UserOpenid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_openid
     *
     * @mbggenerated
     */
    UserOpenid selectByPrimaryKey(Integer user_openid_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_openid
     *
     * @mbggenerated
     */
    List<UserOpenid> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_openid
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserOpenid record);
}