package com.xinshan.dao;

import com.xinshan.model.UserStage;
import java.util.List;

public interface UserStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer user_stage_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stage
     *
     * @mbggenerated
     */
    int insert(UserStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stage
     *
     * @mbggenerated
     */
    UserStage selectByPrimaryKey(Integer user_stage_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stage
     *
     * @mbggenerated
     */
    List<UserStage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserStage record);
}