package com.xinshan.model;

import java.math.BigDecimal;

public class ActivityValueAdded {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_value_added.activity_value_added_id
     *
     * @mbggenerated
     */
    private Integer activity_value_added_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_value_added.activity_id
     *
     * @mbggenerated
     */
    private Integer activity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_value_added.value_added_card_num
     *
     * @mbggenerated
     */
    private Integer value_added_card_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_value_added.value_added_card_amount
     *
     * @mbggenerated
     */
    private BigDecimal value_added_card_amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_value_added.activity_value_added_id
     *
     * @return the value of activity_value_added.activity_value_added_id
     *
     * @mbggenerated
     */
    public Integer getActivity_value_added_id() {
        return activity_value_added_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_value_added.activity_value_added_id
     *
     * @param activity_value_added_id the value for activity_value_added.activity_value_added_id
     *
     * @mbggenerated
     */
    public void setActivity_value_added_id(Integer activity_value_added_id) {
        this.activity_value_added_id = activity_value_added_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_value_added.activity_id
     *
     * @return the value of activity_value_added.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivity_id() {
        return activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_value_added.activity_id
     *
     * @param activity_id the value for activity_value_added.activity_id
     *
     * @mbggenerated
     */
    public void setActivity_id(Integer activity_id) {
        this.activity_id = activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_value_added.value_added_card_num
     *
     * @return the value of activity_value_added.value_added_card_num
     *
     * @mbggenerated
     */
    public Integer getValue_added_card_num() {
        return value_added_card_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_value_added.value_added_card_num
     *
     * @param value_added_card_num the value for activity_value_added.value_added_card_num
     *
     * @mbggenerated
     */
    public void setValue_added_card_num(Integer value_added_card_num) {
        this.value_added_card_num = value_added_card_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_value_added.value_added_card_amount
     *
     * @return the value of activity_value_added.value_added_card_amount
     *
     * @mbggenerated
     */
    public BigDecimal getValue_added_card_amount() {
        return value_added_card_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_value_added.value_added_card_amount
     *
     * @param value_added_card_amount the value for activity_value_added.value_added_card_amount
     *
     * @mbggenerated
     */
    public void setValue_added_card_amount(BigDecimal value_added_card_amount) {
        this.value_added_card_amount = value_added_card_amount;
    }
}