package com.xinshan.model;

import java.math.BigDecimal;

public class ActivityCashBack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_cash_back.activity_cash_back_id
     *
     * @mbggenerated
     */
    private Integer activity_cash_back_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_cash_back.activity_id
     *
     * @mbggenerated
     */
    private Integer activity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_cash_back.cash_back_all
     *
     * @mbggenerated
     */
    private Integer cash_back_all;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_cash_back.cash_back_rate
     *
     * @mbggenerated
     */
    private BigDecimal cash_back_rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_cash_back.cash_back_type
     *
     * @mbggenerated
     */
    private Integer cash_back_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_cash_back.activity_cash_back_remark
     *
     * @mbggenerated
     */
    private String activity_cash_back_remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_cash_back.cash_back_supplier_ids
     *
     * @mbggenerated
     */
    private String cash_back_supplier_ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_cash_back.cash_back_supplier_serieses
     *
     * @mbggenerated
     */
    private String cash_back_supplier_serieses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_cash_back.cash_back_commodity_ids
     *
     * @mbggenerated
     */
    private String cash_back_commodity_ids;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_cash_back.activity_cash_back_id
     *
     * @return the value of activity_cash_back.activity_cash_back_id
     *
     * @mbggenerated
     */
    public Integer getActivity_cash_back_id() {
        return activity_cash_back_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_cash_back.activity_cash_back_id
     *
     * @param activity_cash_back_id the value for activity_cash_back.activity_cash_back_id
     *
     * @mbggenerated
     */
    public void setActivity_cash_back_id(Integer activity_cash_back_id) {
        this.activity_cash_back_id = activity_cash_back_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_cash_back.activity_id
     *
     * @return the value of activity_cash_back.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivity_id() {
        return activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_cash_back.activity_id
     *
     * @param activity_id the value for activity_cash_back.activity_id
     *
     * @mbggenerated
     */
    public void setActivity_id(Integer activity_id) {
        this.activity_id = activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_cash_back.cash_back_all
     *
     * @return the value of activity_cash_back.cash_back_all
     *
     * @mbggenerated
     */
    public Integer getCash_back_all() {
        return cash_back_all;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_cash_back.cash_back_all
     *
     * @param cash_back_all the value for activity_cash_back.cash_back_all
     *
     * @mbggenerated
     */
    public void setCash_back_all(Integer cash_back_all) {
        this.cash_back_all = cash_back_all;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_cash_back.cash_back_rate
     *
     * @return the value of activity_cash_back.cash_back_rate
     *
     * @mbggenerated
     */
    public BigDecimal getCash_back_rate() {
        return cash_back_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_cash_back.cash_back_rate
     *
     * @param cash_back_rate the value for activity_cash_back.cash_back_rate
     *
     * @mbggenerated
     */
    public void setCash_back_rate(BigDecimal cash_back_rate) {
        this.cash_back_rate = cash_back_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_cash_back.cash_back_type
     *
     * @return the value of activity_cash_back.cash_back_type
     *
     * @mbggenerated
     */
    public Integer getCash_back_type() {
        return cash_back_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_cash_back.cash_back_type
     *
     * @param cash_back_type the value for activity_cash_back.cash_back_type
     *
     * @mbggenerated
     */
    public void setCash_back_type(Integer cash_back_type) {
        this.cash_back_type = cash_back_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_cash_back.activity_cash_back_remark
     *
     * @return the value of activity_cash_back.activity_cash_back_remark
     *
     * @mbggenerated
     */
    public String getActivity_cash_back_remark() {
        return activity_cash_back_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_cash_back.activity_cash_back_remark
     *
     * @param activity_cash_back_remark the value for activity_cash_back.activity_cash_back_remark
     *
     * @mbggenerated
     */
    public void setActivity_cash_back_remark(String activity_cash_back_remark) {
        this.activity_cash_back_remark = activity_cash_back_remark == null ? null : activity_cash_back_remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_cash_back.cash_back_supplier_ids
     *
     * @return the value of activity_cash_back.cash_back_supplier_ids
     *
     * @mbggenerated
     */
    public String getCash_back_supplier_ids() {
        return cash_back_supplier_ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_cash_back.cash_back_supplier_ids
     *
     * @param cash_back_supplier_ids the value for activity_cash_back.cash_back_supplier_ids
     *
     * @mbggenerated
     */
    public void setCash_back_supplier_ids(String cash_back_supplier_ids) {
        this.cash_back_supplier_ids = cash_back_supplier_ids == null ? null : cash_back_supplier_ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_cash_back.cash_back_supplier_serieses
     *
     * @return the value of activity_cash_back.cash_back_supplier_serieses
     *
     * @mbggenerated
     */
    public String getCash_back_supplier_serieses() {
        return cash_back_supplier_serieses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_cash_back.cash_back_supplier_serieses
     *
     * @param cash_back_supplier_serieses the value for activity_cash_back.cash_back_supplier_serieses
     *
     * @mbggenerated
     */
    public void setCash_back_supplier_serieses(String cash_back_supplier_serieses) {
        this.cash_back_supplier_serieses = cash_back_supplier_serieses == null ? null : cash_back_supplier_serieses.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_cash_back.cash_back_commodity_ids
     *
     * @return the value of activity_cash_back.cash_back_commodity_ids
     *
     * @mbggenerated
     */
    public String getCash_back_commodity_ids() {
        return cash_back_commodity_ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_cash_back.cash_back_commodity_ids
     *
     * @param cash_back_commodity_ids the value for activity_cash_back.cash_back_commodity_ids
     *
     * @mbggenerated
     */
    public void setCash_back_commodity_ids(String cash_back_commodity_ids) {
        this.cash_back_commodity_ids = cash_back_commodity_ids == null ? null : cash_back_commodity_ids.trim();
    }
}