package com.xinshan.model;

import java.util.Date;

public class AfterSalesCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.after_sales_commodity_id
     *
     * @mbggenerated
     */
    private Integer after_sales_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.after_sales_id
     *
     * @mbggenerated
     */
    private Integer after_sales_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.order_commodity_id
     *
     * @mbggenerated
     */
    private Integer order_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.commodity_problem_fix_status
     *
     * @mbggenerated
     */
    private Integer commodity_problem_fix_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.commodity_problem_resolve_date
     *
     * @mbggenerated
     */
    private Date commodity_problem_resolve_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.after_sales_type
     *
     * @mbggenerated
     */
    private Integer after_sales_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.commodity_problem_return_status
     *
     * @mbggenerated
     */
    private Integer commodity_problem_return_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.return_pay_status
     *
     * @mbggenerated
     */
    private Integer return_pay_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales_commodity.commodity_problem_desc
     *
     * @mbggenerated
     */
    private String commodity_problem_desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.after_sales_commodity_id
     *
     * @return the value of after_sales_commodity.after_sales_commodity_id
     *
     * @mbggenerated
     */
    public Integer getAfter_sales_commodity_id() {
        return after_sales_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.after_sales_commodity_id
     *
     * @param after_sales_commodity_id the value for after_sales_commodity.after_sales_commodity_id
     *
     * @mbggenerated
     */
    public void setAfter_sales_commodity_id(Integer after_sales_commodity_id) {
        this.after_sales_commodity_id = after_sales_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.after_sales_id
     *
     * @return the value of after_sales_commodity.after_sales_id
     *
     * @mbggenerated
     */
    public Integer getAfter_sales_id() {
        return after_sales_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.after_sales_id
     *
     * @param after_sales_id the value for after_sales_commodity.after_sales_id
     *
     * @mbggenerated
     */
    public void setAfter_sales_id(Integer after_sales_id) {
        this.after_sales_id = after_sales_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.order_commodity_id
     *
     * @return the value of after_sales_commodity.order_commodity_id
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_id() {
        return order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.order_commodity_id
     *
     * @param order_commodity_id the value for after_sales_commodity.order_commodity_id
     *
     * @mbggenerated
     */
    public void setOrder_commodity_id(Integer order_commodity_id) {
        this.order_commodity_id = order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.commodity_id
     *
     * @return the value of after_sales_commodity.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_id() {
        return commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.commodity_id
     *
     * @param commodity_id the value for after_sales_commodity.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodity_id(Integer commodity_id) {
        this.commodity_id = commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.commodity_problem_fix_status
     *
     * @return the value of after_sales_commodity.commodity_problem_fix_status
     *
     * @mbggenerated
     */
    public Integer getCommodity_problem_fix_status() {
        return commodity_problem_fix_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.commodity_problem_fix_status
     *
     * @param commodity_problem_fix_status the value for after_sales_commodity.commodity_problem_fix_status
     *
     * @mbggenerated
     */
    public void setCommodity_problem_fix_status(Integer commodity_problem_fix_status) {
        this.commodity_problem_fix_status = commodity_problem_fix_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.commodity_problem_resolve_date
     *
     * @return the value of after_sales_commodity.commodity_problem_resolve_date
     *
     * @mbggenerated
     */
    public Date getCommodity_problem_resolve_date() {
        return commodity_problem_resolve_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.commodity_problem_resolve_date
     *
     * @param commodity_problem_resolve_date the value for after_sales_commodity.commodity_problem_resolve_date
     *
     * @mbggenerated
     */
    public void setCommodity_problem_resolve_date(Date commodity_problem_resolve_date) {
        this.commodity_problem_resolve_date = commodity_problem_resolve_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.after_sales_type
     *
     * @return the value of after_sales_commodity.after_sales_type
     *
     * @mbggenerated
     */
    public Integer getAfter_sales_type() {
        return after_sales_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.after_sales_type
     *
     * @param after_sales_type the value for after_sales_commodity.after_sales_type
     *
     * @mbggenerated
     */
    public void setAfter_sales_type(Integer after_sales_type) {
        this.after_sales_type = after_sales_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.commodity_problem_return_status
     *
     * @return the value of after_sales_commodity.commodity_problem_return_status
     *
     * @mbggenerated
     */
    public Integer getCommodity_problem_return_status() {
        return commodity_problem_return_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.commodity_problem_return_status
     *
     * @param commodity_problem_return_status the value for after_sales_commodity.commodity_problem_return_status
     *
     * @mbggenerated
     */
    public void setCommodity_problem_return_status(Integer commodity_problem_return_status) {
        this.commodity_problem_return_status = commodity_problem_return_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.return_pay_status
     *
     * @return the value of after_sales_commodity.return_pay_status
     *
     * @mbggenerated
     */
    public Integer getReturn_pay_status() {
        return return_pay_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.return_pay_status
     *
     * @param return_pay_status the value for after_sales_commodity.return_pay_status
     *
     * @mbggenerated
     */
    public void setReturn_pay_status(Integer return_pay_status) {
        this.return_pay_status = return_pay_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales_commodity.commodity_problem_desc
     *
     * @return the value of after_sales_commodity.commodity_problem_desc
     *
     * @mbggenerated
     */
    public String getCommodity_problem_desc() {
        return commodity_problem_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales_commodity.commodity_problem_desc
     *
     * @param commodity_problem_desc the value for after_sales_commodity.commodity_problem_desc
     *
     * @mbggenerated
     */
    public void setCommodity_problem_desc(String commodity_problem_desc) {
        this.commodity_problem_desc = commodity_problem_desc == null ? null : commodity_problem_desc.trim();
    }
}