package com.xinshan.model;

import java.util.Date;

public class AfterSales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.after_sales_id
     *
     * @mbggenerated
     */
    private Integer after_sales_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.record_date
     *
     * @mbggenerated
     */
    private Date record_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.order_id
     *
     * @mbggenerated
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.after_sales_status
     *
     * @mbggenerated
     */
    private Integer after_sales_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.resolve_date
     *
     * @mbggenerated
     */
    private Date resolve_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.record_employee_code
     *
     * @mbggenerated
     */
    private String record_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.record_employee_name
     *
     * @mbggenerated
     */
    private String record_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.after_sales_fee_status
     *
     * @mbggenerated
     */
    private Integer after_sales_fee_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.problem_desc
     *
     * @mbggenerated
     */
    private String problem_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sales.order_fee_ids
     *
     * @mbggenerated
     */
    private String order_fee_ids;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.after_sales_id
     *
     * @return the value of after_sales.after_sales_id
     *
     * @mbggenerated
     */
    public Integer getAfter_sales_id() {
        return after_sales_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.after_sales_id
     *
     * @param after_sales_id the value for after_sales.after_sales_id
     *
     * @mbggenerated
     */
    public void setAfter_sales_id(Integer after_sales_id) {
        this.after_sales_id = after_sales_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.record_date
     *
     * @return the value of after_sales.record_date
     *
     * @mbggenerated
     */
    public Date getRecord_date() {
        return record_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.record_date
     *
     * @param record_date the value for after_sales.record_date
     *
     * @mbggenerated
     */
    public void setRecord_date(Date record_date) {
        this.record_date = record_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.order_id
     *
     * @return the value of after_sales.order_id
     *
     * @mbggenerated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.order_id
     *
     * @param order_id the value for after_sales.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.after_sales_status
     *
     * @return the value of after_sales.after_sales_status
     *
     * @mbggenerated
     */
    public Integer getAfter_sales_status() {
        return after_sales_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.after_sales_status
     *
     * @param after_sales_status the value for after_sales.after_sales_status
     *
     * @mbggenerated
     */
    public void setAfter_sales_status(Integer after_sales_status) {
        this.after_sales_status = after_sales_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.resolve_date
     *
     * @return the value of after_sales.resolve_date
     *
     * @mbggenerated
     */
    public Date getResolve_date() {
        return resolve_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.resolve_date
     *
     * @param resolve_date the value for after_sales.resolve_date
     *
     * @mbggenerated
     */
    public void setResolve_date(Date resolve_date) {
        this.resolve_date = resolve_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.record_employee_code
     *
     * @return the value of after_sales.record_employee_code
     *
     * @mbggenerated
     */
    public String getRecord_employee_code() {
        return record_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.record_employee_code
     *
     * @param record_employee_code the value for after_sales.record_employee_code
     *
     * @mbggenerated
     */
    public void setRecord_employee_code(String record_employee_code) {
        this.record_employee_code = record_employee_code == null ? null : record_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.record_employee_name
     *
     * @return the value of after_sales.record_employee_name
     *
     * @mbggenerated
     */
    public String getRecord_employee_name() {
        return record_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.record_employee_name
     *
     * @param record_employee_name the value for after_sales.record_employee_name
     *
     * @mbggenerated
     */
    public void setRecord_employee_name(String record_employee_name) {
        this.record_employee_name = record_employee_name == null ? null : record_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.after_sales_fee_status
     *
     * @return the value of after_sales.after_sales_fee_status
     *
     * @mbggenerated
     */
    public Integer getAfter_sales_fee_status() {
        return after_sales_fee_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.after_sales_fee_status
     *
     * @param after_sales_fee_status the value for after_sales.after_sales_fee_status
     *
     * @mbggenerated
     */
    public void setAfter_sales_fee_status(Integer after_sales_fee_status) {
        this.after_sales_fee_status = after_sales_fee_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.problem_desc
     *
     * @return the value of after_sales.problem_desc
     *
     * @mbggenerated
     */
    public String getProblem_desc() {
        return problem_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.problem_desc
     *
     * @param problem_desc the value for after_sales.problem_desc
     *
     * @mbggenerated
     */
    public void setProblem_desc(String problem_desc) {
        this.problem_desc = problem_desc == null ? null : problem_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sales.order_fee_ids
     *
     * @return the value of after_sales.order_fee_ids
     *
     * @mbggenerated
     */
    public String getOrder_fee_ids() {
        return order_fee_ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sales.order_fee_ids
     *
     * @param order_fee_ids the value for after_sales.order_fee_ids
     *
     * @mbggenerated
     */
    public void setOrder_fee_ids(String order_fee_ids) {
        this.order_fee_ids = order_fee_ids == null ? null : order_fee_ids.trim();
    }
}