package com.xinshan.model;

import java.math.BigDecimal;
import java.util.Date;

public class BrandBoost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.brand_boost_id
     *
     * @mbggenerated
     */
    private Integer brand_boost_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.activity_id
     *
     * @mbggenerated
     */
    private Integer activity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.user_id
     *
     * @mbggenerated
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.receipt_code
     *
     * @mbggenerated
     */
    private String receipt_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.receipt_amount
     *
     * @mbggenerated
     */
    private BigDecimal receipt_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.brand_name
     *
     * @mbggenerated
     */
    private String brand_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.brand_boost_create_employee_name
     *
     * @mbggenerated
     */
    private String brand_boost_create_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.brand_boost_create_employee_code
     *
     * @mbggenerated
     */
    private String brand_boost_create_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.brand_boost_create_date
     *
     * @mbggenerated
     */
    private Date brand_boost_create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_boost.brand_boost_remark
     *
     * @mbggenerated
     */
    private String brand_boost_remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.brand_boost_id
     *
     * @return the value of brand_boost.brand_boost_id
     *
     * @mbggenerated
     */
    public Integer getBrand_boost_id() {
        return brand_boost_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.brand_boost_id
     *
     * @param brand_boost_id the value for brand_boost.brand_boost_id
     *
     * @mbggenerated
     */
    public void setBrand_boost_id(Integer brand_boost_id) {
        this.brand_boost_id = brand_boost_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.activity_id
     *
     * @return the value of brand_boost.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivity_id() {
        return activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.activity_id
     *
     * @param activity_id the value for brand_boost.activity_id
     *
     * @mbggenerated
     */
    public void setActivity_id(Integer activity_id) {
        this.activity_id = activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.user_id
     *
     * @return the value of brand_boost.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.user_id
     *
     * @param user_id the value for brand_boost.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.receipt_code
     *
     * @return the value of brand_boost.receipt_code
     *
     * @mbggenerated
     */
    public String getReceipt_code() {
        return receipt_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.receipt_code
     *
     * @param receipt_code the value for brand_boost.receipt_code
     *
     * @mbggenerated
     */
    public void setReceipt_code(String receipt_code) {
        this.receipt_code = receipt_code == null ? null : receipt_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.receipt_amount
     *
     * @return the value of brand_boost.receipt_amount
     *
     * @mbggenerated
     */
    public BigDecimal getReceipt_amount() {
        return receipt_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.receipt_amount
     *
     * @param receipt_amount the value for brand_boost.receipt_amount
     *
     * @mbggenerated
     */
    public void setReceipt_amount(BigDecimal receipt_amount) {
        this.receipt_amount = receipt_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.brand_name
     *
     * @return the value of brand_boost.brand_name
     *
     * @mbggenerated
     */
    public String getBrand_name() {
        return brand_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.brand_name
     *
     * @param brand_name the value for brand_boost.brand_name
     *
     * @mbggenerated
     */
    public void setBrand_name(String brand_name) {
        this.brand_name = brand_name == null ? null : brand_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.brand_boost_create_employee_name
     *
     * @return the value of brand_boost.brand_boost_create_employee_name
     *
     * @mbggenerated
     */
    public String getBrand_boost_create_employee_name() {
        return brand_boost_create_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.brand_boost_create_employee_name
     *
     * @param brand_boost_create_employee_name the value for brand_boost.brand_boost_create_employee_name
     *
     * @mbggenerated
     */
    public void setBrand_boost_create_employee_name(String brand_boost_create_employee_name) {
        this.brand_boost_create_employee_name = brand_boost_create_employee_name == null ? null : brand_boost_create_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.brand_boost_create_employee_code
     *
     * @return the value of brand_boost.brand_boost_create_employee_code
     *
     * @mbggenerated
     */
    public String getBrand_boost_create_employee_code() {
        return brand_boost_create_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.brand_boost_create_employee_code
     *
     * @param brand_boost_create_employee_code the value for brand_boost.brand_boost_create_employee_code
     *
     * @mbggenerated
     */
    public void setBrand_boost_create_employee_code(String brand_boost_create_employee_code) {
        this.brand_boost_create_employee_code = brand_boost_create_employee_code == null ? null : brand_boost_create_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.brand_boost_create_date
     *
     * @return the value of brand_boost.brand_boost_create_date
     *
     * @mbggenerated
     */
    public Date getBrand_boost_create_date() {
        return brand_boost_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.brand_boost_create_date
     *
     * @param brand_boost_create_date the value for brand_boost.brand_boost_create_date
     *
     * @mbggenerated
     */
    public void setBrand_boost_create_date(Date brand_boost_create_date) {
        this.brand_boost_create_date = brand_boost_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_boost.brand_boost_remark
     *
     * @return the value of brand_boost.brand_boost_remark
     *
     * @mbggenerated
     */
    public String getBrand_boost_remark() {
        return brand_boost_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_boost.brand_boost_remark
     *
     * @param brand_boost_remark the value for brand_boost.brand_boost_remark
     *
     * @mbggenerated
     */
    public void setBrand_boost_remark(String brand_boost_remark) {
        this.brand_boost_remark = brand_boost_remark == null ? null : brand_boost_remark.trim();
    }
}