package com.xinshan.model;

import java.math.BigDecimal;
import java.util.Date;

public class CashBack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.cash_back_id
     *
     * @mbggenerated
     */
    private Integer cash_back_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.order_id
     *
     * @mbggenerated
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.cash_back_create_date
     *
     * @mbggenerated
     */
    private Date cash_back_create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.cash_back_employee_code
     *
     * @mbggenerated
     */
    private String cash_back_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.cash_back_employee_name
     *
     * @mbggenerated
     */
    private String cash_back_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.cash_back_amount
     *
     * @mbggenerated
     */
    private BigDecimal cash_back_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.cash_back_real_amount
     *
     * @mbggenerated
     */
    private BigDecimal cash_back_real_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.activity_id
     *
     * @mbggenerated
     */
    private Integer activity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.cash_back_date
     *
     * @mbggenerated
     */
    private Date cash_back_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.cash_back_type
     *
     * @mbggenerated
     */
    private Integer cash_back_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.order_return_id
     *
     * @mbggenerated
     */
    private Integer order_return_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_back.cash_back_remark
     *
     * @mbggenerated
     */
    private String cash_back_remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.cash_back_id
     *
     * @return the value of cash_back.cash_back_id
     *
     * @mbggenerated
     */
    public Integer getCash_back_id() {
        return cash_back_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.cash_back_id
     *
     * @param cash_back_id the value for cash_back.cash_back_id
     *
     * @mbggenerated
     */
    public void setCash_back_id(Integer cash_back_id) {
        this.cash_back_id = cash_back_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.order_id
     *
     * @return the value of cash_back.order_id
     *
     * @mbggenerated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.order_id
     *
     * @param order_id the value for cash_back.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.cash_back_create_date
     *
     * @return the value of cash_back.cash_back_create_date
     *
     * @mbggenerated
     */
    public Date getCash_back_create_date() {
        return cash_back_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.cash_back_create_date
     *
     * @param cash_back_create_date the value for cash_back.cash_back_create_date
     *
     * @mbggenerated
     */
    public void setCash_back_create_date(Date cash_back_create_date) {
        this.cash_back_create_date = cash_back_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.cash_back_employee_code
     *
     * @return the value of cash_back.cash_back_employee_code
     *
     * @mbggenerated
     */
    public String getCash_back_employee_code() {
        return cash_back_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.cash_back_employee_code
     *
     * @param cash_back_employee_code the value for cash_back.cash_back_employee_code
     *
     * @mbggenerated
     */
    public void setCash_back_employee_code(String cash_back_employee_code) {
        this.cash_back_employee_code = cash_back_employee_code == null ? null : cash_back_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.cash_back_employee_name
     *
     * @return the value of cash_back.cash_back_employee_name
     *
     * @mbggenerated
     */
    public String getCash_back_employee_name() {
        return cash_back_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.cash_back_employee_name
     *
     * @param cash_back_employee_name the value for cash_back.cash_back_employee_name
     *
     * @mbggenerated
     */
    public void setCash_back_employee_name(String cash_back_employee_name) {
        this.cash_back_employee_name = cash_back_employee_name == null ? null : cash_back_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.cash_back_amount
     *
     * @return the value of cash_back.cash_back_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCash_back_amount() {
        return cash_back_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.cash_back_amount
     *
     * @param cash_back_amount the value for cash_back.cash_back_amount
     *
     * @mbggenerated
     */
    public void setCash_back_amount(BigDecimal cash_back_amount) {
        this.cash_back_amount = cash_back_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.cash_back_real_amount
     *
     * @return the value of cash_back.cash_back_real_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCash_back_real_amount() {
        return cash_back_real_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.cash_back_real_amount
     *
     * @param cash_back_real_amount the value for cash_back.cash_back_real_amount
     *
     * @mbggenerated
     */
    public void setCash_back_real_amount(BigDecimal cash_back_real_amount) {
        this.cash_back_real_amount = cash_back_real_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.activity_id
     *
     * @return the value of cash_back.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivity_id() {
        return activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.activity_id
     *
     * @param activity_id the value for cash_back.activity_id
     *
     * @mbggenerated
     */
    public void setActivity_id(Integer activity_id) {
        this.activity_id = activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.cash_back_date
     *
     * @return the value of cash_back.cash_back_date
     *
     * @mbggenerated
     */
    public Date getCash_back_date() {
        return cash_back_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.cash_back_date
     *
     * @param cash_back_date the value for cash_back.cash_back_date
     *
     * @mbggenerated
     */
    public void setCash_back_date(Date cash_back_date) {
        this.cash_back_date = cash_back_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.cash_back_type
     *
     * @return the value of cash_back.cash_back_type
     *
     * @mbggenerated
     */
    public Integer getCash_back_type() {
        return cash_back_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.cash_back_type
     *
     * @param cash_back_type the value for cash_back.cash_back_type
     *
     * @mbggenerated
     */
    public void setCash_back_type(Integer cash_back_type) {
        this.cash_back_type = cash_back_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.order_return_id
     *
     * @return the value of cash_back.order_return_id
     *
     * @mbggenerated
     */
    public Integer getOrder_return_id() {
        return order_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.order_return_id
     *
     * @param order_return_id the value for cash_back.order_return_id
     *
     * @mbggenerated
     */
    public void setOrder_return_id(Integer order_return_id) {
        this.order_return_id = order_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_back.cash_back_remark
     *
     * @return the value of cash_back.cash_back_remark
     *
     * @mbggenerated
     */
    public String getCash_back_remark() {
        return cash_back_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_back.cash_back_remark
     *
     * @param cash_back_remark the value for cash_back.cash_back_remark
     *
     * @mbggenerated
     */
    public void setCash_back_remark(String cash_back_remark) {
        this.cash_back_remark = cash_back_remark == null ? null : cash_back_remark.trim();
    }
}