package com.xinshan.model;

public class CategoryAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_attribute.category_attribute_id
     *
     * @mbggenerated
     */
    private Integer category_attribute_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_attribute.category_attribute_type
     *
     * @mbggenerated
     */
    private Integer category_attribute_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_attribute.category_attribute_name
     *
     * @mbggenerated
     */
    private String category_attribute_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_attribute.category_attribute_order
     *
     * @mbggenerated
     */
    private Integer category_attribute_order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_attribute.category_id
     *
     * @mbggenerated
     */
    private Integer category_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_attribute.category_attribute_value
     *
     * @mbggenerated
     */
    private String category_attribute_value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_attribute.category_attribute_id
     *
     * @return the value of category_attribute.category_attribute_id
     *
     * @mbggenerated
     */
    public Integer getCategory_attribute_id() {
        return category_attribute_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_attribute.category_attribute_id
     *
     * @param category_attribute_id the value for category_attribute.category_attribute_id
     *
     * @mbggenerated
     */
    public void setCategory_attribute_id(Integer category_attribute_id) {
        this.category_attribute_id = category_attribute_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_attribute.category_attribute_type
     *
     * @return the value of category_attribute.category_attribute_type
     *
     * @mbggenerated
     */
    public Integer getCategory_attribute_type() {
        return category_attribute_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_attribute.category_attribute_type
     *
     * @param category_attribute_type the value for category_attribute.category_attribute_type
     *
     * @mbggenerated
     */
    public void setCategory_attribute_type(Integer category_attribute_type) {
        this.category_attribute_type = category_attribute_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_attribute.category_attribute_name
     *
     * @return the value of category_attribute.category_attribute_name
     *
     * @mbggenerated
     */
    public String getCategory_attribute_name() {
        return category_attribute_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_attribute.category_attribute_name
     *
     * @param category_attribute_name the value for category_attribute.category_attribute_name
     *
     * @mbggenerated
     */
    public void setCategory_attribute_name(String category_attribute_name) {
        this.category_attribute_name = category_attribute_name == null ? null : category_attribute_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_attribute.category_attribute_order
     *
     * @return the value of category_attribute.category_attribute_order
     *
     * @mbggenerated
     */
    public Integer getCategory_attribute_order() {
        return category_attribute_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_attribute.category_attribute_order
     *
     * @param category_attribute_order the value for category_attribute.category_attribute_order
     *
     * @mbggenerated
     */
    public void setCategory_attribute_order(Integer category_attribute_order) {
        this.category_attribute_order = category_attribute_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_attribute.category_id
     *
     * @return the value of category_attribute.category_id
     *
     * @mbggenerated
     */
    public Integer getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_attribute.category_id
     *
     * @param category_id the value for category_attribute.category_id
     *
     * @mbggenerated
     */
    public void setCategory_id(Integer category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_attribute.category_attribute_value
     *
     * @return the value of category_attribute.category_attribute_value
     *
     * @mbggenerated
     */
    public String getCategory_attribute_value() {
        return category_attribute_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_attribute.category_attribute_value
     *
     * @param category_attribute_value the value for category_attribute.category_attribute_value
     *
     * @mbggenerated
     */
    public void setCategory_attribute_value(String category_attribute_value) {
        this.category_attribute_value = category_attribute_value == null ? null : category_attribute_value.trim();
    }
}