package com.xinshan.model;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbggenerated
     */
    private Integer category_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_parent_id
     *
     * @mbggenerated
     */
    private Integer category_parent_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbggenerated
     */
    private String category_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_code
     *
     * @mbggenerated
     */
    private String category_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_sort
     *
     * @mbggenerated
     */
    private Integer category_sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.customize_attribute
     *
     * @mbggenerated
     */
    private Integer customize_attribute;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbggenerated
     */
    public Integer getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param category_id the value for category.category_id
     *
     * @mbggenerated
     */
    public void setCategory_id(Integer category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_parent_id
     *
     * @return the value of category.category_parent_id
     *
     * @mbggenerated
     */
    public Integer getCategory_parent_id() {
        return category_parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_parent_id
     *
     * @param category_parent_id the value for category.category_parent_id
     *
     * @mbggenerated
     */
    public void setCategory_parent_id(Integer category_parent_id) {
        this.category_parent_id = category_parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbggenerated
     */
    public String getCategory_name() {
        return category_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param category_name the value for category.category_name
     *
     * @mbggenerated
     */
    public void setCategory_name(String category_name) {
        this.category_name = category_name == null ? null : category_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_code
     *
     * @return the value of category.category_code
     *
     * @mbggenerated
     */
    public String getCategory_code() {
        return category_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_code
     *
     * @param category_code the value for category.category_code
     *
     * @mbggenerated
     */
    public void setCategory_code(String category_code) {
        this.category_code = category_code == null ? null : category_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_sort
     *
     * @return the value of category.category_sort
     *
     * @mbggenerated
     */
    public Integer getCategory_sort() {
        return category_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_sort
     *
     * @param category_sort the value for category.category_sort
     *
     * @mbggenerated
     */
    public void setCategory_sort(Integer category_sort) {
        this.category_sort = category_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.customize_attribute
     *
     * @return the value of category.customize_attribute
     *
     * @mbggenerated
     */
    public Integer getCustomize_attribute() {
        return customize_attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.customize_attribute
     *
     * @param customize_attribute the value for category.customize_attribute
     *
     * @mbggenerated
     */
    public void setCustomize_attribute(Integer customize_attribute) {
        this.customize_attribute = customize_attribute;
    }
}