package com.xinshan.model;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbggenerated
     */
    private Integer city_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_zip
     *
     * @mbggenerated
     */
    private String city_zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbggenerated
     */
    private String city_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.province_zip
     *
     * @mbggenerated
     */
    private String province_zip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_id
     *
     * @return the value of city.city_id
     *
     * @mbggenerated
     */
    public Integer getCity_id() {
        return city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_id
     *
     * @param city_id the value for city.city_id
     *
     * @mbggenerated
     */
    public void setCity_id(Integer city_id) {
        this.city_id = city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_zip
     *
     * @return the value of city.city_zip
     *
     * @mbggenerated
     */
    public String getCity_zip() {
        return city_zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_zip
     *
     * @param city_zip the value for city.city_zip
     *
     * @mbggenerated
     */
    public void setCity_zip(String city_zip) {
        this.city_zip = city_zip == null ? null : city_zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbggenerated
     */
    public String getCity_name() {
        return city_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param city_name the value for city.city_name
     *
     * @mbggenerated
     */
    public void setCity_name(String city_name) {
        this.city_name = city_name == null ? null : city_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.province_zip
     *
     * @return the value of city.province_zip
     *
     * @mbggenerated
     */
    public String getProvince_zip() {
        return province_zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.province_zip
     *
     * @param province_zip the value for city.province_zip
     *
     * @mbggenerated
     */
    public void setProvince_zip(String province_zip) {
        this.province_zip = province_zip == null ? null : province_zip.trim();
    }
}