package com.xinshan.model;

import java.math.BigDecimal;

public class CommoditySampleInDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in_detail.commodity_sample_in_detail_id
     *
     * @mbggenerated
     */
    private Integer commodity_sample_in_detail_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in_detail.commodity_sample_in_id
     *
     * @mbggenerated
     */
    private Integer commodity_sample_in_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in_detail.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in_detail.sample_in_detail_sample
     *
     * @mbggenerated
     */
    private Integer sample_in_detail_sample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in_detail.commodity_sample_in_num
     *
     * @mbggenerated
     */
    private Integer commodity_sample_in_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in_detail.sample_in_detail_confirm_status
     *
     * @mbggenerated
     */
    private Integer sample_in_detail_confirm_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in_detail.inventory_in_commodity_id
     *
     * @mbggenerated
     */
    private Integer inventory_in_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in_detail.sample_in_freight
     *
     * @mbggenerated
     */
    private BigDecimal sample_in_freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in_detail.sample_in_detail_remark
     *
     * @mbggenerated
     */
    private String sample_in_detail_remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in_detail.commodity_sample_in_detail_id
     *
     * @return the value of commodity_sample_in_detail.commodity_sample_in_detail_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_sample_in_detail_id() {
        return commodity_sample_in_detail_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in_detail.commodity_sample_in_detail_id
     *
     * @param commodity_sample_in_detail_id the value for commodity_sample_in_detail.commodity_sample_in_detail_id
     *
     * @mbggenerated
     */
    public void setCommodity_sample_in_detail_id(Integer commodity_sample_in_detail_id) {
        this.commodity_sample_in_detail_id = commodity_sample_in_detail_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in_detail.commodity_sample_in_id
     *
     * @return the value of commodity_sample_in_detail.commodity_sample_in_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_sample_in_id() {
        return commodity_sample_in_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in_detail.commodity_sample_in_id
     *
     * @param commodity_sample_in_id the value for commodity_sample_in_detail.commodity_sample_in_id
     *
     * @mbggenerated
     */
    public void setCommodity_sample_in_id(Integer commodity_sample_in_id) {
        this.commodity_sample_in_id = commodity_sample_in_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in_detail.commodity_id
     *
     * @return the value of commodity_sample_in_detail.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_id() {
        return commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in_detail.commodity_id
     *
     * @param commodity_id the value for commodity_sample_in_detail.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodity_id(Integer commodity_id) {
        this.commodity_id = commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in_detail.sample_in_detail_sample
     *
     * @return the value of commodity_sample_in_detail.sample_in_detail_sample
     *
     * @mbggenerated
     */
    public Integer getSample_in_detail_sample() {
        return sample_in_detail_sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in_detail.sample_in_detail_sample
     *
     * @param sample_in_detail_sample the value for commodity_sample_in_detail.sample_in_detail_sample
     *
     * @mbggenerated
     */
    public void setSample_in_detail_sample(Integer sample_in_detail_sample) {
        this.sample_in_detail_sample = sample_in_detail_sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in_detail.commodity_sample_in_num
     *
     * @return the value of commodity_sample_in_detail.commodity_sample_in_num
     *
     * @mbggenerated
     */
    public Integer getCommodity_sample_in_num() {
        return commodity_sample_in_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in_detail.commodity_sample_in_num
     *
     * @param commodity_sample_in_num the value for commodity_sample_in_detail.commodity_sample_in_num
     *
     * @mbggenerated
     */
    public void setCommodity_sample_in_num(Integer commodity_sample_in_num) {
        this.commodity_sample_in_num = commodity_sample_in_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in_detail.sample_in_detail_confirm_status
     *
     * @return the value of commodity_sample_in_detail.sample_in_detail_confirm_status
     *
     * @mbggenerated
     */
    public Integer getSample_in_detail_confirm_status() {
        return sample_in_detail_confirm_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in_detail.sample_in_detail_confirm_status
     *
     * @param sample_in_detail_confirm_status the value for commodity_sample_in_detail.sample_in_detail_confirm_status
     *
     * @mbggenerated
     */
    public void setSample_in_detail_confirm_status(Integer sample_in_detail_confirm_status) {
        this.sample_in_detail_confirm_status = sample_in_detail_confirm_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in_detail.inventory_in_commodity_id
     *
     * @return the value of commodity_sample_in_detail.inventory_in_commodity_id
     *
     * @mbggenerated
     */
    public Integer getInventory_in_commodity_id() {
        return inventory_in_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in_detail.inventory_in_commodity_id
     *
     * @param inventory_in_commodity_id the value for commodity_sample_in_detail.inventory_in_commodity_id
     *
     * @mbggenerated
     */
    public void setInventory_in_commodity_id(Integer inventory_in_commodity_id) {
        this.inventory_in_commodity_id = inventory_in_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in_detail.sample_in_freight
     *
     * @return the value of commodity_sample_in_detail.sample_in_freight
     *
     * @mbggenerated
     */
    public BigDecimal getSample_in_freight() {
        return sample_in_freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in_detail.sample_in_freight
     *
     * @param sample_in_freight the value for commodity_sample_in_detail.sample_in_freight
     *
     * @mbggenerated
     */
    public void setSample_in_freight(BigDecimal sample_in_freight) {
        this.sample_in_freight = sample_in_freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in_detail.sample_in_detail_remark
     *
     * @return the value of commodity_sample_in_detail.sample_in_detail_remark
     *
     * @mbggenerated
     */
    public String getSample_in_detail_remark() {
        return sample_in_detail_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in_detail.sample_in_detail_remark
     *
     * @param sample_in_detail_remark the value for commodity_sample_in_detail.sample_in_detail_remark
     *
     * @mbggenerated
     */
    public void setSample_in_detail_remark(String sample_in_detail_remark) {
        this.sample_in_detail_remark = sample_in_detail_remark == null ? null : sample_in_detail_remark.trim();
    }
}