package com.xinshan.model;

import java.util.Date;

public class CommoditySampleIn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.commodity_sample_in_id
     *
     * @mbggenerated
     */
    private Integer commodity_sample_in_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.sample_in_code
     *
     * @mbggenerated
     */
    private String sample_in_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.sample_in_create_date
     *
     * @mbggenerated
     */
    private Date sample_in_create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.sample_in_employee_code
     *
     * @mbggenerated
     */
    private String sample_in_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.sample_in_employee_name
     *
     * @mbggenerated
     */
    private String sample_in_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.sample_in_date
     *
     * @mbggenerated
     */
    private Date sample_in_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.sample_in_supplier_id
     *
     * @mbggenerated
     */
    private Integer sample_in_supplier_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.commodity_store_id
     *
     * @mbggenerated
     */
    private Integer commodity_store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.sample_in_confirm_status
     *
     * @mbggenerated
     */
    private Integer sample_in_confirm_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.inventory_in_id
     *
     * @mbggenerated
     */
    private Integer inventory_in_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_sample_in.sample_in_remark
     *
     * @mbggenerated
     */
    private String sample_in_remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.commodity_sample_in_id
     *
     * @return the value of commodity_sample_in.commodity_sample_in_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_sample_in_id() {
        return commodity_sample_in_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.commodity_sample_in_id
     *
     * @param commodity_sample_in_id the value for commodity_sample_in.commodity_sample_in_id
     *
     * @mbggenerated
     */
    public void setCommodity_sample_in_id(Integer commodity_sample_in_id) {
        this.commodity_sample_in_id = commodity_sample_in_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.sample_in_code
     *
     * @return the value of commodity_sample_in.sample_in_code
     *
     * @mbggenerated
     */
    public String getSample_in_code() {
        return sample_in_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.sample_in_code
     *
     * @param sample_in_code the value for commodity_sample_in.sample_in_code
     *
     * @mbggenerated
     */
    public void setSample_in_code(String sample_in_code) {
        this.sample_in_code = sample_in_code == null ? null : sample_in_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.sample_in_create_date
     *
     * @return the value of commodity_sample_in.sample_in_create_date
     *
     * @mbggenerated
     */
    public Date getSample_in_create_date() {
        return sample_in_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.sample_in_create_date
     *
     * @param sample_in_create_date the value for commodity_sample_in.sample_in_create_date
     *
     * @mbggenerated
     */
    public void setSample_in_create_date(Date sample_in_create_date) {
        this.sample_in_create_date = sample_in_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.sample_in_employee_code
     *
     * @return the value of commodity_sample_in.sample_in_employee_code
     *
     * @mbggenerated
     */
    public String getSample_in_employee_code() {
        return sample_in_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.sample_in_employee_code
     *
     * @param sample_in_employee_code the value for commodity_sample_in.sample_in_employee_code
     *
     * @mbggenerated
     */
    public void setSample_in_employee_code(String sample_in_employee_code) {
        this.sample_in_employee_code = sample_in_employee_code == null ? null : sample_in_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.sample_in_employee_name
     *
     * @return the value of commodity_sample_in.sample_in_employee_name
     *
     * @mbggenerated
     */
    public String getSample_in_employee_name() {
        return sample_in_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.sample_in_employee_name
     *
     * @param sample_in_employee_name the value for commodity_sample_in.sample_in_employee_name
     *
     * @mbggenerated
     */
    public void setSample_in_employee_name(String sample_in_employee_name) {
        this.sample_in_employee_name = sample_in_employee_name == null ? null : sample_in_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.sample_in_date
     *
     * @return the value of commodity_sample_in.sample_in_date
     *
     * @mbggenerated
     */
    public Date getSample_in_date() {
        return sample_in_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.sample_in_date
     *
     * @param sample_in_date the value for commodity_sample_in.sample_in_date
     *
     * @mbggenerated
     */
    public void setSample_in_date(Date sample_in_date) {
        this.sample_in_date = sample_in_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.sample_in_supplier_id
     *
     * @return the value of commodity_sample_in.sample_in_supplier_id
     *
     * @mbggenerated
     */
    public Integer getSample_in_supplier_id() {
        return sample_in_supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.sample_in_supplier_id
     *
     * @param sample_in_supplier_id the value for commodity_sample_in.sample_in_supplier_id
     *
     * @mbggenerated
     */
    public void setSample_in_supplier_id(Integer sample_in_supplier_id) {
        this.sample_in_supplier_id = sample_in_supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.commodity_store_id
     *
     * @return the value of commodity_sample_in.commodity_store_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_store_id() {
        return commodity_store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.commodity_store_id
     *
     * @param commodity_store_id the value for commodity_sample_in.commodity_store_id
     *
     * @mbggenerated
     */
    public void setCommodity_store_id(Integer commodity_store_id) {
        this.commodity_store_id = commodity_store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.sample_in_confirm_status
     *
     * @return the value of commodity_sample_in.sample_in_confirm_status
     *
     * @mbggenerated
     */
    public Integer getSample_in_confirm_status() {
        return sample_in_confirm_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.sample_in_confirm_status
     *
     * @param sample_in_confirm_status the value for commodity_sample_in.sample_in_confirm_status
     *
     * @mbggenerated
     */
    public void setSample_in_confirm_status(Integer sample_in_confirm_status) {
        this.sample_in_confirm_status = sample_in_confirm_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.inventory_in_id
     *
     * @return the value of commodity_sample_in.inventory_in_id
     *
     * @mbggenerated
     */
    public Integer getInventory_in_id() {
        return inventory_in_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.inventory_in_id
     *
     * @param inventory_in_id the value for commodity_sample_in.inventory_in_id
     *
     * @mbggenerated
     */
    public void setInventory_in_id(Integer inventory_in_id) {
        this.inventory_in_id = inventory_in_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_sample_in.sample_in_remark
     *
     * @return the value of commodity_sample_in.sample_in_remark
     *
     * @mbggenerated
     */
    public String getSample_in_remark() {
        return sample_in_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_sample_in.sample_in_remark
     *
     * @param sample_in_remark the value for commodity_sample_in.sample_in_remark
     *
     * @mbggenerated
     */
    public void setSample_in_remark(String sample_in_remark) {
        this.sample_in_remark = sample_in_remark == null ? null : sample_in_remark.trim();
    }
}