package com.xinshan.model;

public class CommodityColor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_color.commodity_color_id
     *
     * @mbggenerated
     */
    private Integer commodity_color_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_color.color_name
     *
     * @mbggenerated
     */
    private String color_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_color.commodity_color_id
     *
     * @return the value of commodity_color.commodity_color_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_color_id() {
        return commodity_color_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_color.commodity_color_id
     *
     * @param commodity_color_id the value for commodity_color.commodity_color_id
     *
     * @mbggenerated
     */
    public void setCommodity_color_id(Integer commodity_color_id) {
        this.commodity_color_id = commodity_color_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_color.color_name
     *
     * @return the value of commodity_color.color_name
     *
     * @mbggenerated
     */
    public String getColor_name() {
        return color_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_color.color_name
     *
     * @param color_name the value for commodity_color.color_name
     *
     * @mbggenerated
     */
    public void setColor_name(String color_name) {
        this.color_name = color_name == null ? null : color_name.trim();
    }
}