package com.xinshan.model;

import java.math.BigDecimal;

public class EmployeePerformance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.employee_performance_id
     *
     * @mbggenerated
     */
    private Integer employee_performance_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.performance_year
     *
     * @mbggenerated
     */
    private Integer performance_year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.performance_month
     *
     * @mbggenerated
     */
    private Integer performance_month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.employee_code
     *
     * @mbggenerated
     */
    private String employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.order_commodity_amount
     *
     * @mbggenerated
     */
    private BigDecimal order_commodity_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.order_commodity_num
     *
     * @mbggenerated
     */
    private Integer order_commodity_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.order_num
     *
     * @mbggenerated
     */
    private Integer order_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.order_return_commodity_amount
     *
     * @mbggenerated
     */
    private BigDecimal order_return_commodity_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.order_return_commodity_num
     *
     * @mbggenerated
     */
    private Integer order_return_commodity_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.order_return_commodity_add_amount
     *
     * @mbggenerated
     */
    private BigDecimal order_return_commodity_add_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.order_return_commodity_add_num
     *
     * @mbggenerated
     */
    private Integer order_return_commodity_add_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.gift_commodity_amount
     *
     * @mbggenerated
     */
    private BigDecimal gift_commodity_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.gift_commodity_num
     *
     * @mbggenerated
     */
    private Integer gift_commodity_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.gift_return_commodity_amount
     *
     * @mbggenerated
     */
    private BigDecimal gift_return_commodity_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.gift_return_commodity_num
     *
     * @mbggenerated
     */
    private Integer gift_return_commodity_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.sell_amount
     *
     * @mbggenerated
     */
    private BigDecimal sell_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.add_up_sell_amount
     *
     * @mbggenerated
     */
    private BigDecimal add_up_sell_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.add_up_order_num
     *
     * @mbggenerated
     */
    private Integer add_up_order_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_performance.add_up_commodity_num
     *
     * @mbggenerated
     */
    private Integer add_up_commodity_num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.employee_performance_id
     *
     * @return the value of employee_performance.employee_performance_id
     *
     * @mbggenerated
     */
    public Integer getEmployee_performance_id() {
        return employee_performance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.employee_performance_id
     *
     * @param employee_performance_id the value for employee_performance.employee_performance_id
     *
     * @mbggenerated
     */
    public void setEmployee_performance_id(Integer employee_performance_id) {
        this.employee_performance_id = employee_performance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.performance_year
     *
     * @return the value of employee_performance.performance_year
     *
     * @mbggenerated
     */
    public Integer getPerformance_year() {
        return performance_year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.performance_year
     *
     * @param performance_year the value for employee_performance.performance_year
     *
     * @mbggenerated
     */
    public void setPerformance_year(Integer performance_year) {
        this.performance_year = performance_year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.performance_month
     *
     * @return the value of employee_performance.performance_month
     *
     * @mbggenerated
     */
    public Integer getPerformance_month() {
        return performance_month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.performance_month
     *
     * @param performance_month the value for employee_performance.performance_month
     *
     * @mbggenerated
     */
    public void setPerformance_month(Integer performance_month) {
        this.performance_month = performance_month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.employee_code
     *
     * @return the value of employee_performance.employee_code
     *
     * @mbggenerated
     */
    public String getEmployee_code() {
        return employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.employee_code
     *
     * @param employee_code the value for employee_performance.employee_code
     *
     * @mbggenerated
     */
    public void setEmployee_code(String employee_code) {
        this.employee_code = employee_code == null ? null : employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.order_commodity_amount
     *
     * @return the value of employee_performance.order_commodity_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOrder_commodity_amount() {
        return order_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.order_commodity_amount
     *
     * @param order_commodity_amount the value for employee_performance.order_commodity_amount
     *
     * @mbggenerated
     */
    public void setOrder_commodity_amount(BigDecimal order_commodity_amount) {
        this.order_commodity_amount = order_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.order_commodity_num
     *
     * @return the value of employee_performance.order_commodity_num
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_num() {
        return order_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.order_commodity_num
     *
     * @param order_commodity_num the value for employee_performance.order_commodity_num
     *
     * @mbggenerated
     */
    public void setOrder_commodity_num(Integer order_commodity_num) {
        this.order_commodity_num = order_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.order_num
     *
     * @return the value of employee_performance.order_num
     *
     * @mbggenerated
     */
    public Integer getOrder_num() {
        return order_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.order_num
     *
     * @param order_num the value for employee_performance.order_num
     *
     * @mbggenerated
     */
    public void setOrder_num(Integer order_num) {
        this.order_num = order_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.order_return_commodity_amount
     *
     * @return the value of employee_performance.order_return_commodity_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOrder_return_commodity_amount() {
        return order_return_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.order_return_commodity_amount
     *
     * @param order_return_commodity_amount the value for employee_performance.order_return_commodity_amount
     *
     * @mbggenerated
     */
    public void setOrder_return_commodity_amount(BigDecimal order_return_commodity_amount) {
        this.order_return_commodity_amount = order_return_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.order_return_commodity_num
     *
     * @return the value of employee_performance.order_return_commodity_num
     *
     * @mbggenerated
     */
    public Integer getOrder_return_commodity_num() {
        return order_return_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.order_return_commodity_num
     *
     * @param order_return_commodity_num the value for employee_performance.order_return_commodity_num
     *
     * @mbggenerated
     */
    public void setOrder_return_commodity_num(Integer order_return_commodity_num) {
        this.order_return_commodity_num = order_return_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.order_return_commodity_add_amount
     *
     * @return the value of employee_performance.order_return_commodity_add_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOrder_return_commodity_add_amount() {
        return order_return_commodity_add_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.order_return_commodity_add_amount
     *
     * @param order_return_commodity_add_amount the value for employee_performance.order_return_commodity_add_amount
     *
     * @mbggenerated
     */
    public void setOrder_return_commodity_add_amount(BigDecimal order_return_commodity_add_amount) {
        this.order_return_commodity_add_amount = order_return_commodity_add_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.order_return_commodity_add_num
     *
     * @return the value of employee_performance.order_return_commodity_add_num
     *
     * @mbggenerated
     */
    public Integer getOrder_return_commodity_add_num() {
        return order_return_commodity_add_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.order_return_commodity_add_num
     *
     * @param order_return_commodity_add_num the value for employee_performance.order_return_commodity_add_num
     *
     * @mbggenerated
     */
    public void setOrder_return_commodity_add_num(Integer order_return_commodity_add_num) {
        this.order_return_commodity_add_num = order_return_commodity_add_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.gift_commodity_amount
     *
     * @return the value of employee_performance.gift_commodity_amount
     *
     * @mbggenerated
     */
    public BigDecimal getGift_commodity_amount() {
        return gift_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.gift_commodity_amount
     *
     * @param gift_commodity_amount the value for employee_performance.gift_commodity_amount
     *
     * @mbggenerated
     */
    public void setGift_commodity_amount(BigDecimal gift_commodity_amount) {
        this.gift_commodity_amount = gift_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.gift_commodity_num
     *
     * @return the value of employee_performance.gift_commodity_num
     *
     * @mbggenerated
     */
    public Integer getGift_commodity_num() {
        return gift_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.gift_commodity_num
     *
     * @param gift_commodity_num the value for employee_performance.gift_commodity_num
     *
     * @mbggenerated
     */
    public void setGift_commodity_num(Integer gift_commodity_num) {
        this.gift_commodity_num = gift_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.gift_return_commodity_amount
     *
     * @return the value of employee_performance.gift_return_commodity_amount
     *
     * @mbggenerated
     */
    public BigDecimal getGift_return_commodity_amount() {
        return gift_return_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.gift_return_commodity_amount
     *
     * @param gift_return_commodity_amount the value for employee_performance.gift_return_commodity_amount
     *
     * @mbggenerated
     */
    public void setGift_return_commodity_amount(BigDecimal gift_return_commodity_amount) {
        this.gift_return_commodity_amount = gift_return_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.gift_return_commodity_num
     *
     * @return the value of employee_performance.gift_return_commodity_num
     *
     * @mbggenerated
     */
    public Integer getGift_return_commodity_num() {
        return gift_return_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.gift_return_commodity_num
     *
     * @param gift_return_commodity_num the value for employee_performance.gift_return_commodity_num
     *
     * @mbggenerated
     */
    public void setGift_return_commodity_num(Integer gift_return_commodity_num) {
        this.gift_return_commodity_num = gift_return_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.sell_amount
     *
     * @return the value of employee_performance.sell_amount
     *
     * @mbggenerated
     */
    public BigDecimal getSell_amount() {
        return sell_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.sell_amount
     *
     * @param sell_amount the value for employee_performance.sell_amount
     *
     * @mbggenerated
     */
    public void setSell_amount(BigDecimal sell_amount) {
        this.sell_amount = sell_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.add_up_sell_amount
     *
     * @return the value of employee_performance.add_up_sell_amount
     *
     * @mbggenerated
     */
    public BigDecimal getAdd_up_sell_amount() {
        return add_up_sell_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.add_up_sell_amount
     *
     * @param add_up_sell_amount the value for employee_performance.add_up_sell_amount
     *
     * @mbggenerated
     */
    public void setAdd_up_sell_amount(BigDecimal add_up_sell_amount) {
        this.add_up_sell_amount = add_up_sell_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.add_up_order_num
     *
     * @return the value of employee_performance.add_up_order_num
     *
     * @mbggenerated
     */
    public Integer getAdd_up_order_num() {
        return add_up_order_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.add_up_order_num
     *
     * @param add_up_order_num the value for employee_performance.add_up_order_num
     *
     * @mbggenerated
     */
    public void setAdd_up_order_num(Integer add_up_order_num) {
        this.add_up_order_num = add_up_order_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_performance.add_up_commodity_num
     *
     * @return the value of employee_performance.add_up_commodity_num
     *
     * @mbggenerated
     */
    public Integer getAdd_up_commodity_num() {
        return add_up_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_performance.add_up_commodity_num
     *
     * @param add_up_commodity_num the value for employee_performance.add_up_commodity_num
     *
     * @mbggenerated
     */
    public void setAdd_up_commodity_num(Integer add_up_commodity_num) {
        this.add_up_commodity_num = add_up_commodity_num;
    }
}