package com.xinshan.model;

import java.util.Date;

public class Gift {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_id
     *
     * @mbggenerated
     */
    private Integer gift_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_code
     *
     * @mbggenerated
     */
    private String gift_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.user_id
     *
     * @mbggenerated
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_type
     *
     * @mbggenerated
     */
    private Integer gift_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.order_id
     *
     * @mbggenerated
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.activity_id
     *
     * @mbggenerated
     */
    private Integer activity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.expense_type
     *
     * @mbggenerated
     */
    private Integer expense_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplier_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_create_employee_code
     *
     * @mbggenerated
     */
    private String gift_create_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_create_employee_name
     *
     * @mbggenerated
     */
    private String gift_create_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_create_date
     *
     * @mbggenerated
     */
    private Date gift_create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_return_status
     *
     * @mbggenerated
     */
    private Integer gift_return_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_return_employee_code
     *
     * @mbggenerated
     */
    private String gift_return_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_return_employee_name
     *
     * @mbggenerated
     */
    private String gift_return_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_return_date
     *
     * @mbggenerated
     */
    private Date gift_return_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_settlement_status
     *
     * @mbggenerated
     */
    private Integer gift_settlement_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_out_status
     *
     * @mbggenerated
     */
    private Integer gift_out_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_enable
     *
     * @mbggenerated
     */
    private Integer gift_enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_purchase_status
     *
     * @mbggenerated
     */
    private Integer gift_purchase_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_remark
     *
     * @mbggenerated
     */
    private String gift_remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.gift_return_remark
     *
     * @mbggenerated
     */
    private String gift_return_remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_id
     *
     * @return the value of gift.gift_id
     *
     * @mbggenerated
     */
    public Integer getGift_id() {
        return gift_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_id
     *
     * @param gift_id the value for gift.gift_id
     *
     * @mbggenerated
     */
    public void setGift_id(Integer gift_id) {
        this.gift_id = gift_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_code
     *
     * @return the value of gift.gift_code
     *
     * @mbggenerated
     */
    public String getGift_code() {
        return gift_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_code
     *
     * @param gift_code the value for gift.gift_code
     *
     * @mbggenerated
     */
    public void setGift_code(String gift_code) {
        this.gift_code = gift_code == null ? null : gift_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.user_id
     *
     * @return the value of gift.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.user_id
     *
     * @param user_id the value for gift.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_type
     *
     * @return the value of gift.gift_type
     *
     * @mbggenerated
     */
    public Integer getGift_type() {
        return gift_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_type
     *
     * @param gift_type the value for gift.gift_type
     *
     * @mbggenerated
     */
    public void setGift_type(Integer gift_type) {
        this.gift_type = gift_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.order_id
     *
     * @return the value of gift.order_id
     *
     * @mbggenerated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.order_id
     *
     * @param order_id the value for gift.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.activity_id
     *
     * @return the value of gift.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivity_id() {
        return activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.activity_id
     *
     * @param activity_id the value for gift.activity_id
     *
     * @mbggenerated
     */
    public void setActivity_id(Integer activity_id) {
        this.activity_id = activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.expense_type
     *
     * @return the value of gift.expense_type
     *
     * @mbggenerated
     */
    public Integer getExpense_type() {
        return expense_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.expense_type
     *
     * @param expense_type the value for gift.expense_type
     *
     * @mbggenerated
     */
    public void setExpense_type(Integer expense_type) {
        this.expense_type = expense_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.supplier_id
     *
     * @return the value of gift.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplier_id() {
        return supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.supplier_id
     *
     * @param supplier_id the value for gift.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplier_id(Integer supplier_id) {
        this.supplier_id = supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_create_employee_code
     *
     * @return the value of gift.gift_create_employee_code
     *
     * @mbggenerated
     */
    public String getGift_create_employee_code() {
        return gift_create_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_create_employee_code
     *
     * @param gift_create_employee_code the value for gift.gift_create_employee_code
     *
     * @mbggenerated
     */
    public void setGift_create_employee_code(String gift_create_employee_code) {
        this.gift_create_employee_code = gift_create_employee_code == null ? null : gift_create_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_create_employee_name
     *
     * @return the value of gift.gift_create_employee_name
     *
     * @mbggenerated
     */
    public String getGift_create_employee_name() {
        return gift_create_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_create_employee_name
     *
     * @param gift_create_employee_name the value for gift.gift_create_employee_name
     *
     * @mbggenerated
     */
    public void setGift_create_employee_name(String gift_create_employee_name) {
        this.gift_create_employee_name = gift_create_employee_name == null ? null : gift_create_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_create_date
     *
     * @return the value of gift.gift_create_date
     *
     * @mbggenerated
     */
    public Date getGift_create_date() {
        return gift_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_create_date
     *
     * @param gift_create_date the value for gift.gift_create_date
     *
     * @mbggenerated
     */
    public void setGift_create_date(Date gift_create_date) {
        this.gift_create_date = gift_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_return_status
     *
     * @return the value of gift.gift_return_status
     *
     * @mbggenerated
     */
    public Integer getGift_return_status() {
        return gift_return_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_return_status
     *
     * @param gift_return_status the value for gift.gift_return_status
     *
     * @mbggenerated
     */
    public void setGift_return_status(Integer gift_return_status) {
        this.gift_return_status = gift_return_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_return_employee_code
     *
     * @return the value of gift.gift_return_employee_code
     *
     * @mbggenerated
     */
    public String getGift_return_employee_code() {
        return gift_return_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_return_employee_code
     *
     * @param gift_return_employee_code the value for gift.gift_return_employee_code
     *
     * @mbggenerated
     */
    public void setGift_return_employee_code(String gift_return_employee_code) {
        this.gift_return_employee_code = gift_return_employee_code == null ? null : gift_return_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_return_employee_name
     *
     * @return the value of gift.gift_return_employee_name
     *
     * @mbggenerated
     */
    public String getGift_return_employee_name() {
        return gift_return_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_return_employee_name
     *
     * @param gift_return_employee_name the value for gift.gift_return_employee_name
     *
     * @mbggenerated
     */
    public void setGift_return_employee_name(String gift_return_employee_name) {
        this.gift_return_employee_name = gift_return_employee_name == null ? null : gift_return_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_return_date
     *
     * @return the value of gift.gift_return_date
     *
     * @mbggenerated
     */
    public Date getGift_return_date() {
        return gift_return_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_return_date
     *
     * @param gift_return_date the value for gift.gift_return_date
     *
     * @mbggenerated
     */
    public void setGift_return_date(Date gift_return_date) {
        this.gift_return_date = gift_return_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_settlement_status
     *
     * @return the value of gift.gift_settlement_status
     *
     * @mbggenerated
     */
    public Integer getGift_settlement_status() {
        return gift_settlement_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_settlement_status
     *
     * @param gift_settlement_status the value for gift.gift_settlement_status
     *
     * @mbggenerated
     */
    public void setGift_settlement_status(Integer gift_settlement_status) {
        this.gift_settlement_status = gift_settlement_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_out_status
     *
     * @return the value of gift.gift_out_status
     *
     * @mbggenerated
     */
    public Integer getGift_out_status() {
        return gift_out_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_out_status
     *
     * @param gift_out_status the value for gift.gift_out_status
     *
     * @mbggenerated
     */
    public void setGift_out_status(Integer gift_out_status) {
        this.gift_out_status = gift_out_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_enable
     *
     * @return the value of gift.gift_enable
     *
     * @mbggenerated
     */
    public Integer getGift_enable() {
        return gift_enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_enable
     *
     * @param gift_enable the value for gift.gift_enable
     *
     * @mbggenerated
     */
    public void setGift_enable(Integer gift_enable) {
        this.gift_enable = gift_enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_purchase_status
     *
     * @return the value of gift.gift_purchase_status
     *
     * @mbggenerated
     */
    public Integer getGift_purchase_status() {
        return gift_purchase_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_purchase_status
     *
     * @param gift_purchase_status the value for gift.gift_purchase_status
     *
     * @mbggenerated
     */
    public void setGift_purchase_status(Integer gift_purchase_status) {
        this.gift_purchase_status = gift_purchase_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_remark
     *
     * @return the value of gift.gift_remark
     *
     * @mbggenerated
     */
    public String getGift_remark() {
        return gift_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_remark
     *
     * @param gift_remark the value for gift.gift_remark
     *
     * @mbggenerated
     */
    public void setGift_remark(String gift_remark) {
        this.gift_remark = gift_remark == null ? null : gift_remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gift_return_remark
     *
     * @return the value of gift.gift_return_remark
     *
     * @mbggenerated
     */
    public String getGift_return_remark() {
        return gift_return_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gift_return_remark
     *
     * @param gift_return_remark the value for gift.gift_return_remark
     *
     * @mbggenerated
     */
    public void setGift_return_remark(String gift_return_remark) {
        this.gift_return_remark = gift_return_remark == null ? null : gift_return_remark.trim();
    }
}