package com.xinshan.model;

public class GiftReturnCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_return_commodity.gift_return_commodity_id
     *
     * @mbggenerated
     */
    private Integer gift_return_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_return_commodity.gift_return_id
     *
     * @mbggenerated
     */
    private Integer gift_return_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_return_commodity.return_num
     *
     * @mbggenerated
     */
    private Integer return_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_return_commodity.gift_commodity_id
     *
     * @mbggenerated
     */
    private Integer gift_commodity_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_return_commodity.gift_return_commodity_id
     *
     * @return the value of gift_return_commodity.gift_return_commodity_id
     *
     * @mbggenerated
     */
    public Integer getGift_return_commodity_id() {
        return gift_return_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_return_commodity.gift_return_commodity_id
     *
     * @param gift_return_commodity_id the value for gift_return_commodity.gift_return_commodity_id
     *
     * @mbggenerated
     */
    public void setGift_return_commodity_id(Integer gift_return_commodity_id) {
        this.gift_return_commodity_id = gift_return_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_return_commodity.gift_return_id
     *
     * @return the value of gift_return_commodity.gift_return_id
     *
     * @mbggenerated
     */
    public Integer getGift_return_id() {
        return gift_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_return_commodity.gift_return_id
     *
     * @param gift_return_id the value for gift_return_commodity.gift_return_id
     *
     * @mbggenerated
     */
    public void setGift_return_id(Integer gift_return_id) {
        this.gift_return_id = gift_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_return_commodity.return_num
     *
     * @return the value of gift_return_commodity.return_num
     *
     * @mbggenerated
     */
    public Integer getReturn_num() {
        return return_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_return_commodity.return_num
     *
     * @param return_num the value for gift_return_commodity.return_num
     *
     * @mbggenerated
     */
    public void setReturn_num(Integer return_num) {
        this.return_num = return_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_return_commodity.gift_commodity_id
     *
     * @return the value of gift_return_commodity.gift_commodity_id
     *
     * @mbggenerated
     */
    public Integer getGift_commodity_id() {
        return gift_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_return_commodity.gift_commodity_id
     *
     * @param gift_commodity_id the value for gift_return_commodity.gift_commodity_id
     *
     * @mbggenerated
     */
    public void setGift_commodity_id(Integer gift_commodity_id) {
        this.gift_commodity_id = gift_commodity_id;
    }
}