package com.xinshan.model;

public class InventoryMoveCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_move_commodity.inventory_move_commodity_id
     *
     * @mbggenerated
     */
    private Integer inventory_move_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_move_commodity.inventory_move_id
     *
     * @mbggenerated
     */
    private Integer inventory_move_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_move_commodity.commodity_num_id1
     *
     * @mbggenerated
     */
    private Integer commodity_num_id1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_move_commodity.commodity_num_id2
     *
     * @mbggenerated
     */
    private Integer commodity_num_id2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_move_commodity.inventory_move_num
     *
     * @mbggenerated
     */
    private Integer inventory_move_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_move_commodity.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodity_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_move_commodity.inventory_move_commodity_id
     *
     * @return the value of inventory_move_commodity.inventory_move_commodity_id
     *
     * @mbggenerated
     */
    public Integer getInventory_move_commodity_id() {
        return inventory_move_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_move_commodity.inventory_move_commodity_id
     *
     * @param inventory_move_commodity_id the value for inventory_move_commodity.inventory_move_commodity_id
     *
     * @mbggenerated
     */
    public void setInventory_move_commodity_id(Integer inventory_move_commodity_id) {
        this.inventory_move_commodity_id = inventory_move_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_move_commodity.inventory_move_id
     *
     * @return the value of inventory_move_commodity.inventory_move_id
     *
     * @mbggenerated
     */
    public Integer getInventory_move_id() {
        return inventory_move_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_move_commodity.inventory_move_id
     *
     * @param inventory_move_id the value for inventory_move_commodity.inventory_move_id
     *
     * @mbggenerated
     */
    public void setInventory_move_id(Integer inventory_move_id) {
        this.inventory_move_id = inventory_move_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_move_commodity.commodity_num_id1
     *
     * @return the value of inventory_move_commodity.commodity_num_id1
     *
     * @mbggenerated
     */
    public Integer getCommodity_num_id1() {
        return commodity_num_id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_move_commodity.commodity_num_id1
     *
     * @param commodity_num_id1 the value for inventory_move_commodity.commodity_num_id1
     *
     * @mbggenerated
     */
    public void setCommodity_num_id1(Integer commodity_num_id1) {
        this.commodity_num_id1 = commodity_num_id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_move_commodity.commodity_num_id2
     *
     * @return the value of inventory_move_commodity.commodity_num_id2
     *
     * @mbggenerated
     */
    public Integer getCommodity_num_id2() {
        return commodity_num_id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_move_commodity.commodity_num_id2
     *
     * @param commodity_num_id2 the value for inventory_move_commodity.commodity_num_id2
     *
     * @mbggenerated
     */
    public void setCommodity_num_id2(Integer commodity_num_id2) {
        this.commodity_num_id2 = commodity_num_id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_move_commodity.inventory_move_num
     *
     * @return the value of inventory_move_commodity.inventory_move_num
     *
     * @mbggenerated
     */
    public Integer getInventory_move_num() {
        return inventory_move_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_move_commodity.inventory_move_num
     *
     * @param inventory_move_num the value for inventory_move_commodity.inventory_move_num
     *
     * @mbggenerated
     */
    public void setInventory_move_num(Integer inventory_move_num) {
        this.inventory_move_num = inventory_move_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_move_commodity.commodity_id
     *
     * @return the value of inventory_move_commodity.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_id() {
        return commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_move_commodity.commodity_id
     *
     * @param commodity_id the value for inventory_move_commodity.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodity_id(Integer commodity_id) {
        this.commodity_id = commodity_id;
    }
}