package com.xinshan.model;

public class InventoryOutCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.inventory_out_commodity_id
     *
     * @mbggenerated
     */
    private Integer inventory_out_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.inventory_out_id
     *
     * @mbggenerated
     */
    private Integer inventory_out_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplier_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.inventory_out_total_num
     *
     * @mbggenerated
     */
    private Integer inventory_out_total_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.order_commodity_num
     *
     * @mbggenerated
     */
    private Integer order_commodity_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.inventory_out_commodity_status
     *
     * @mbggenerated
     */
    private Integer inventory_out_commodity_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.sample
     *
     * @mbggenerated
     */
    private Integer sample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.retrun_commodity
     *
     * @mbggenerated
     */
    private Integer retrun_commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.order_commodity_id
     *
     * @mbggenerated
     */
    private Integer order_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out_commodity.gift_commodity_id
     *
     * @mbggenerated
     */
    private Integer gift_commodity_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.inventory_out_commodity_id
     *
     * @return the value of inventory_out_commodity.inventory_out_commodity_id
     *
     * @mbggenerated
     */
    public Integer getInventory_out_commodity_id() {
        return inventory_out_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.inventory_out_commodity_id
     *
     * @param inventory_out_commodity_id the value for inventory_out_commodity.inventory_out_commodity_id
     *
     * @mbggenerated
     */
    public void setInventory_out_commodity_id(Integer inventory_out_commodity_id) {
        this.inventory_out_commodity_id = inventory_out_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.inventory_out_id
     *
     * @return the value of inventory_out_commodity.inventory_out_id
     *
     * @mbggenerated
     */
    public Integer getInventory_out_id() {
        return inventory_out_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.inventory_out_id
     *
     * @param inventory_out_id the value for inventory_out_commodity.inventory_out_id
     *
     * @mbggenerated
     */
    public void setInventory_out_id(Integer inventory_out_id) {
        this.inventory_out_id = inventory_out_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.commodity_id
     *
     * @return the value of inventory_out_commodity.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_id() {
        return commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.commodity_id
     *
     * @param commodity_id the value for inventory_out_commodity.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodity_id(Integer commodity_id) {
        this.commodity_id = commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.supplier_id
     *
     * @return the value of inventory_out_commodity.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplier_id() {
        return supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.supplier_id
     *
     * @param supplier_id the value for inventory_out_commodity.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplier_id(Integer supplier_id) {
        this.supplier_id = supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.inventory_out_total_num
     *
     * @return the value of inventory_out_commodity.inventory_out_total_num
     *
     * @mbggenerated
     */
    public Integer getInventory_out_total_num() {
        return inventory_out_total_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.inventory_out_total_num
     *
     * @param inventory_out_total_num the value for inventory_out_commodity.inventory_out_total_num
     *
     * @mbggenerated
     */
    public void setInventory_out_total_num(Integer inventory_out_total_num) {
        this.inventory_out_total_num = inventory_out_total_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.order_commodity_num
     *
     * @return the value of inventory_out_commodity.order_commodity_num
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_num() {
        return order_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.order_commodity_num
     *
     * @param order_commodity_num the value for inventory_out_commodity.order_commodity_num
     *
     * @mbggenerated
     */
    public void setOrder_commodity_num(Integer order_commodity_num) {
        this.order_commodity_num = order_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.inventory_out_commodity_status
     *
     * @return the value of inventory_out_commodity.inventory_out_commodity_status
     *
     * @mbggenerated
     */
    public Integer getInventory_out_commodity_status() {
        return inventory_out_commodity_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.inventory_out_commodity_status
     *
     * @param inventory_out_commodity_status the value for inventory_out_commodity.inventory_out_commodity_status
     *
     * @mbggenerated
     */
    public void setInventory_out_commodity_status(Integer inventory_out_commodity_status) {
        this.inventory_out_commodity_status = inventory_out_commodity_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.sample
     *
     * @return the value of inventory_out_commodity.sample
     *
     * @mbggenerated
     */
    public Integer getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.sample
     *
     * @param sample the value for inventory_out_commodity.sample
     *
     * @mbggenerated
     */
    public void setSample(Integer sample) {
        this.sample = sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.retrun_commodity
     *
     * @return the value of inventory_out_commodity.retrun_commodity
     *
     * @mbggenerated
     */
    public Integer getRetrun_commodity() {
        return retrun_commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.retrun_commodity
     *
     * @param retrun_commodity the value for inventory_out_commodity.retrun_commodity
     *
     * @mbggenerated
     */
    public void setRetrun_commodity(Integer retrun_commodity) {
        this.retrun_commodity = retrun_commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.order_commodity_id
     *
     * @return the value of inventory_out_commodity.order_commodity_id
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_id() {
        return order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.order_commodity_id
     *
     * @param order_commodity_id the value for inventory_out_commodity.order_commodity_id
     *
     * @mbggenerated
     */
    public void setOrder_commodity_id(Integer order_commodity_id) {
        this.order_commodity_id = order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out_commodity.gift_commodity_id
     *
     * @return the value of inventory_out_commodity.gift_commodity_id
     *
     * @mbggenerated
     */
    public Integer getGift_commodity_id() {
        return gift_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out_commodity.gift_commodity_id
     *
     * @param gift_commodity_id the value for inventory_out_commodity.gift_commodity_id
     *
     * @mbggenerated
     */
    public void setGift_commodity_id(Integer gift_commodity_id) {
        this.gift_commodity_id = gift_commodity_id;
    }
}