package com.xinshan.model;

import java.util.Date;

public class InventoryOut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.inventory_out_id
     *
     * @mbggenerated
     */
    private Integer inventory_out_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.inventory_out_code
     *
     * @mbggenerated
     */
    private String inventory_out_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.order_id
     *
     * @mbggenerated
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.inventory_out_status
     *
     * @mbggenerated
     */
    private Integer inventory_out_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.inventory_out_create_date
     *
     * @mbggenerated
     */
    private Date inventory_out_create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.inventory_out_complete_date
     *
     * @mbggenerated
     */
    private Date inventory_out_complete_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.record_employee_code
     *
     * @mbggenerated
     */
    private String record_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.record_employee_name
     *
     * @mbggenerated
     */
    private String record_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.inventory_out_type
     *
     * @mbggenerated
     */
    private Integer inventory_out_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_out.inventory_out_obj_id
     *
     * @mbggenerated
     */
    private Integer inventory_out_obj_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.inventory_out_id
     *
     * @return the value of inventory_out.inventory_out_id
     *
     * @mbggenerated
     */
    public Integer getInventory_out_id() {
        return inventory_out_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.inventory_out_id
     *
     * @param inventory_out_id the value for inventory_out.inventory_out_id
     *
     * @mbggenerated
     */
    public void setInventory_out_id(Integer inventory_out_id) {
        this.inventory_out_id = inventory_out_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.inventory_out_code
     *
     * @return the value of inventory_out.inventory_out_code
     *
     * @mbggenerated
     */
    public String getInventory_out_code() {
        return inventory_out_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.inventory_out_code
     *
     * @param inventory_out_code the value for inventory_out.inventory_out_code
     *
     * @mbggenerated
     */
    public void setInventory_out_code(String inventory_out_code) {
        this.inventory_out_code = inventory_out_code == null ? null : inventory_out_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.order_id
     *
     * @return the value of inventory_out.order_id
     *
     * @mbggenerated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.order_id
     *
     * @param order_id the value for inventory_out.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.inventory_out_status
     *
     * @return the value of inventory_out.inventory_out_status
     *
     * @mbggenerated
     */
    public Integer getInventory_out_status() {
        return inventory_out_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.inventory_out_status
     *
     * @param inventory_out_status the value for inventory_out.inventory_out_status
     *
     * @mbggenerated
     */
    public void setInventory_out_status(Integer inventory_out_status) {
        this.inventory_out_status = inventory_out_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.inventory_out_create_date
     *
     * @return the value of inventory_out.inventory_out_create_date
     *
     * @mbggenerated
     */
    public Date getInventory_out_create_date() {
        return inventory_out_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.inventory_out_create_date
     *
     * @param inventory_out_create_date the value for inventory_out.inventory_out_create_date
     *
     * @mbggenerated
     */
    public void setInventory_out_create_date(Date inventory_out_create_date) {
        this.inventory_out_create_date = inventory_out_create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.inventory_out_complete_date
     *
     * @return the value of inventory_out.inventory_out_complete_date
     *
     * @mbggenerated
     */
    public Date getInventory_out_complete_date() {
        return inventory_out_complete_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.inventory_out_complete_date
     *
     * @param inventory_out_complete_date the value for inventory_out.inventory_out_complete_date
     *
     * @mbggenerated
     */
    public void setInventory_out_complete_date(Date inventory_out_complete_date) {
        this.inventory_out_complete_date = inventory_out_complete_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.record_employee_code
     *
     * @return the value of inventory_out.record_employee_code
     *
     * @mbggenerated
     */
    public String getRecord_employee_code() {
        return record_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.record_employee_code
     *
     * @param record_employee_code the value for inventory_out.record_employee_code
     *
     * @mbggenerated
     */
    public void setRecord_employee_code(String record_employee_code) {
        this.record_employee_code = record_employee_code == null ? null : record_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.record_employee_name
     *
     * @return the value of inventory_out.record_employee_name
     *
     * @mbggenerated
     */
    public String getRecord_employee_name() {
        return record_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.record_employee_name
     *
     * @param record_employee_name the value for inventory_out.record_employee_name
     *
     * @mbggenerated
     */
    public void setRecord_employee_name(String record_employee_name) {
        this.record_employee_name = record_employee_name == null ? null : record_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.inventory_out_type
     *
     * @return the value of inventory_out.inventory_out_type
     *
     * @mbggenerated
     */
    public Integer getInventory_out_type() {
        return inventory_out_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.inventory_out_type
     *
     * @param inventory_out_type the value for inventory_out.inventory_out_type
     *
     * @mbggenerated
     */
    public void setInventory_out_type(Integer inventory_out_type) {
        this.inventory_out_type = inventory_out_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_out.inventory_out_obj_id
     *
     * @return the value of inventory_out.inventory_out_obj_id
     *
     * @mbggenerated
     */
    public Integer getInventory_out_obj_id() {
        return inventory_out_obj_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_out.inventory_out_obj_id
     *
     * @param inventory_out_obj_id the value for inventory_out.inventory_out_obj_id
     *
     * @mbggenerated
     */
    public void setInventory_out_obj_id(Integer inventory_out_obj_id) {
        this.inventory_out_obj_id = inventory_out_obj_id;
    }
}