package com.xinshan.model;

public class Logistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.logistics_id
     *
     * @mbggenerated
     */
    private Integer logistics_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.logistics_status
     *
     * @mbggenerated
     */
    private Integer logistics_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics.inventory_history_id
     *
     * @mbggenerated
     */
    private Integer inventory_history_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.logistics_id
     *
     * @return the value of logistics.logistics_id
     *
     * @mbggenerated
     */
    public Integer getLogistics_id() {
        return logistics_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.logistics_id
     *
     * @param logistics_id the value for logistics.logistics_id
     *
     * @mbggenerated
     */
    public void setLogistics_id(Integer logistics_id) {
        this.logistics_id = logistics_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.logistics_status
     *
     * @return the value of logistics.logistics_status
     *
     * @mbggenerated
     */
    public Integer getLogistics_status() {
        return logistics_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.logistics_status
     *
     * @param logistics_status the value for logistics.logistics_status
     *
     * @mbggenerated
     */
    public void setLogistics_status(Integer logistics_status) {
        this.logistics_status = logistics_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics.inventory_history_id
     *
     * @return the value of logistics.inventory_history_id
     *
     * @mbggenerated
     */
    public Integer getInventory_history_id() {
        return inventory_history_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics.inventory_history_id
     *
     * @param inventory_history_id the value for logistics.inventory_history_id
     *
     * @mbggenerated
     */
    public void setInventory_history_id(Integer inventory_history_id) {
        this.inventory_history_id = inventory_history_id;
    }
}