package com.xinshan.model;

public class OrderFeeType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_fee_type.order_fee_type_id
     *
     * @mbggenerated
     */
    private Integer order_fee_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_fee_type.order_fee_type_name
     *
     * @mbggenerated
     */
    private String order_fee_type_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_fee_type.order_fee_type_desc
     *
     * @mbggenerated
     */
    private String order_fee_type_desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_fee_type.order_fee_type_id
     *
     * @return the value of order_fee_type.order_fee_type_id
     *
     * @mbggenerated
     */
    public Integer getOrder_fee_type_id() {
        return order_fee_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_fee_type.order_fee_type_id
     *
     * @param order_fee_type_id the value for order_fee_type.order_fee_type_id
     *
     * @mbggenerated
     */
    public void setOrder_fee_type_id(Integer order_fee_type_id) {
        this.order_fee_type_id = order_fee_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_fee_type.order_fee_type_name
     *
     * @return the value of order_fee_type.order_fee_type_name
     *
     * @mbggenerated
     */
    public String getOrder_fee_type_name() {
        return order_fee_type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_fee_type.order_fee_type_name
     *
     * @param order_fee_type_name the value for order_fee_type.order_fee_type_name
     *
     * @mbggenerated
     */
    public void setOrder_fee_type_name(String order_fee_type_name) {
        this.order_fee_type_name = order_fee_type_name == null ? null : order_fee_type_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_fee_type.order_fee_type_desc
     *
     * @return the value of order_fee_type.order_fee_type_desc
     *
     * @mbggenerated
     */
    public String getOrder_fee_type_desc() {
        return order_fee_type_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_fee_type.order_fee_type_desc
     *
     * @param order_fee_type_desc the value for order_fee_type.order_fee_type_desc
     *
     * @mbggenerated
     */
    public void setOrder_fee_type_desc(String order_fee_type_desc) {
        this.order_fee_type_desc = order_fee_type_desc == null ? null : order_fee_type_desc.trim();
    }
}