package com.xinshan.model;

import java.math.BigDecimal;

public class OrderCommodityValueAddedCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_value_added_card.order_commodity_value_added_card_id
     *
     * @mbggenerated
     */
    private Integer order_commodity_value_added_card_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_value_added_card.order_commodity_id
     *
     * @mbggenerated
     */
    private Integer order_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_value_added_card.card_code
     *
     * @mbggenerated
     */
    private String card_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_value_added_card.card_amount
     *
     * @mbggenerated
     */
    private BigDecimal card_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_value_added_card.card_real_amount
     *
     * @mbggenerated
     */
    private BigDecimal card_real_amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_value_added_card.order_commodity_value_added_card_id
     *
     * @return the value of order_commodity_value_added_card.order_commodity_value_added_card_id
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_value_added_card_id() {
        return order_commodity_value_added_card_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_value_added_card.order_commodity_value_added_card_id
     *
     * @param order_commodity_value_added_card_id the value for order_commodity_value_added_card.order_commodity_value_added_card_id
     *
     * @mbggenerated
     */
    public void setOrder_commodity_value_added_card_id(Integer order_commodity_value_added_card_id) {
        this.order_commodity_value_added_card_id = order_commodity_value_added_card_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_value_added_card.order_commodity_id
     *
     * @return the value of order_commodity_value_added_card.order_commodity_id
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_id() {
        return order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_value_added_card.order_commodity_id
     *
     * @param order_commodity_id the value for order_commodity_value_added_card.order_commodity_id
     *
     * @mbggenerated
     */
    public void setOrder_commodity_id(Integer order_commodity_id) {
        this.order_commodity_id = order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_value_added_card.card_code
     *
     * @return the value of order_commodity_value_added_card.card_code
     *
     * @mbggenerated
     */
    public String getCard_code() {
        return card_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_value_added_card.card_code
     *
     * @param card_code the value for order_commodity_value_added_card.card_code
     *
     * @mbggenerated
     */
    public void setCard_code(String card_code) {
        this.card_code = card_code == null ? null : card_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_value_added_card.card_amount
     *
     * @return the value of order_commodity_value_added_card.card_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCard_amount() {
        return card_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_value_added_card.card_amount
     *
     * @param card_amount the value for order_commodity_value_added_card.card_amount
     *
     * @mbggenerated
     */
    public void setCard_amount(BigDecimal card_amount) {
        this.card_amount = card_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_value_added_card.card_real_amount
     *
     * @return the value of order_commodity_value_added_card.card_real_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCard_real_amount() {
        return card_real_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_value_added_card.card_real_amount
     *
     * @param card_real_amount the value for order_commodity_value_added_card.card_real_amount
     *
     * @mbggenerated
     */
    public void setCard_real_amount(BigDecimal card_real_amount) {
        this.card_real_amount = card_real_amount;
    }
}