package com.xinshan.model;

import java.math.BigDecimal;

public class OrderCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.order_commodity_id
     *
     * @mbggenerated
     */
    private Integer order_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.order_id
     *
     * @mbggenerated
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.unit_price
     *
     * @mbggenerated
     */
    private BigDecimal unit_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.commodity_total_price
     *
     * @mbggenerated
     */
    private BigDecimal commodity_total_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.bargain_price
     *
     * @mbggenerated
     */
    private BigDecimal bargain_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.sample
     *
     * @mbggenerated
     */
    private Integer sample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.order_commodity_status
     *
     * @mbggenerated
     */
    private Integer order_commodity_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.return_commodity
     *
     * @mbggenerated
     */
    private Integer return_commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.order_commodity_return_status
     *
     * @mbggenerated
     */
    private Integer order_commodity_return_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.revision_fee
     *
     * @mbggenerated
     */
    private BigDecimal revision_fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.activity_commodity_id
     *
     * @mbggenerated
     */
    private Integer activity_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.commodity_num
     *
     * @mbggenerated
     */
    private Integer commodity_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.order_commodity_return_num
     *
     * @mbggenerated
     */
    private Integer order_commodity_return_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.order_commodity_num
     *
     * @mbggenerated
     */
    private Integer order_commodity_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.order_commodity_type
     *
     * @mbggenerated
     */
    private Integer order_commodity_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.order_commodity_remark
     *
     * @mbggenerated
     */
    private String order_commodity_remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.revision_size
     *
     * @mbggenerated
     */
    private String revision_size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.order_commodity_id
     *
     * @return the value of order_commodity.order_commodity_id
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_id() {
        return order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.order_commodity_id
     *
     * @param order_commodity_id the value for order_commodity.order_commodity_id
     *
     * @mbggenerated
     */
    public void setOrder_commodity_id(Integer order_commodity_id) {
        this.order_commodity_id = order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.commodity_id
     *
     * @return the value of order_commodity.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodity_id() {
        return commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.commodity_id
     *
     * @param commodity_id the value for order_commodity.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodity_id(Integer commodity_id) {
        this.commodity_id = commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.order_id
     *
     * @return the value of order_commodity.order_id
     *
     * @mbggenerated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.order_id
     *
     * @param order_id the value for order_commodity.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.unit_price
     *
     * @return the value of order_commodity.unit_price
     *
     * @mbggenerated
     */
    public BigDecimal getUnit_price() {
        return unit_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.unit_price
     *
     * @param unit_price the value for order_commodity.unit_price
     *
     * @mbggenerated
     */
    public void setUnit_price(BigDecimal unit_price) {
        this.unit_price = unit_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.commodity_total_price
     *
     * @return the value of order_commodity.commodity_total_price
     *
     * @mbggenerated
     */
    public BigDecimal getCommodity_total_price() {
        return commodity_total_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.commodity_total_price
     *
     * @param commodity_total_price the value for order_commodity.commodity_total_price
     *
     * @mbggenerated
     */
    public void setCommodity_total_price(BigDecimal commodity_total_price) {
        this.commodity_total_price = commodity_total_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.bargain_price
     *
     * @return the value of order_commodity.bargain_price
     *
     * @mbggenerated
     */
    public BigDecimal getBargain_price() {
        return bargain_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.bargain_price
     *
     * @param bargain_price the value for order_commodity.bargain_price
     *
     * @mbggenerated
     */
    public void setBargain_price(BigDecimal bargain_price) {
        this.bargain_price = bargain_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.sample
     *
     * @return the value of order_commodity.sample
     *
     * @mbggenerated
     */
    public Integer getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.sample
     *
     * @param sample the value for order_commodity.sample
     *
     * @mbggenerated
     */
    public void setSample(Integer sample) {
        this.sample = sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.discount
     *
     * @return the value of order_commodity.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.discount
     *
     * @param discount the value for order_commodity.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.order_commodity_status
     *
     * @return the value of order_commodity.order_commodity_status
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_status() {
        return order_commodity_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.order_commodity_status
     *
     * @param order_commodity_status the value for order_commodity.order_commodity_status
     *
     * @mbggenerated
     */
    public void setOrder_commodity_status(Integer order_commodity_status) {
        this.order_commodity_status = order_commodity_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.return_commodity
     *
     * @return the value of order_commodity.return_commodity
     *
     * @mbggenerated
     */
    public Integer getReturn_commodity() {
        return return_commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.return_commodity
     *
     * @param return_commodity the value for order_commodity.return_commodity
     *
     * @mbggenerated
     */
    public void setReturn_commodity(Integer return_commodity) {
        this.return_commodity = return_commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.order_commodity_return_status
     *
     * @return the value of order_commodity.order_commodity_return_status
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_return_status() {
        return order_commodity_return_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.order_commodity_return_status
     *
     * @param order_commodity_return_status the value for order_commodity.order_commodity_return_status
     *
     * @mbggenerated
     */
    public void setOrder_commodity_return_status(Integer order_commodity_return_status) {
        this.order_commodity_return_status = order_commodity_return_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.revision_fee
     *
     * @return the value of order_commodity.revision_fee
     *
     * @mbggenerated
     */
    public BigDecimal getRevision_fee() {
        return revision_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.revision_fee
     *
     * @param revision_fee the value for order_commodity.revision_fee
     *
     * @mbggenerated
     */
    public void setRevision_fee(BigDecimal revision_fee) {
        this.revision_fee = revision_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.activity_commodity_id
     *
     * @return the value of order_commodity.activity_commodity_id
     *
     * @mbggenerated
     */
    public Integer getActivity_commodity_id() {
        return activity_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.activity_commodity_id
     *
     * @param activity_commodity_id the value for order_commodity.activity_commodity_id
     *
     * @mbggenerated
     */
    public void setActivity_commodity_id(Integer activity_commodity_id) {
        this.activity_commodity_id = activity_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.commodity_num
     *
     * @return the value of order_commodity.commodity_num
     *
     * @mbggenerated
     */
    public Integer getCommodity_num() {
        return commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.commodity_num
     *
     * @param commodity_num the value for order_commodity.commodity_num
     *
     * @mbggenerated
     */
    public void setCommodity_num(Integer commodity_num) {
        this.commodity_num = commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.order_commodity_return_num
     *
     * @return the value of order_commodity.order_commodity_return_num
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_return_num() {
        return order_commodity_return_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.order_commodity_return_num
     *
     * @param order_commodity_return_num the value for order_commodity.order_commodity_return_num
     *
     * @mbggenerated
     */
    public void setOrder_commodity_return_num(Integer order_commodity_return_num) {
        this.order_commodity_return_num = order_commodity_return_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.order_commodity_num
     *
     * @return the value of order_commodity.order_commodity_num
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_num() {
        return order_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.order_commodity_num
     *
     * @param order_commodity_num the value for order_commodity.order_commodity_num
     *
     * @mbggenerated
     */
    public void setOrder_commodity_num(Integer order_commodity_num) {
        this.order_commodity_num = order_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.order_commodity_type
     *
     * @return the value of order_commodity.order_commodity_type
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_type() {
        return order_commodity_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.order_commodity_type
     *
     * @param order_commodity_type the value for order_commodity.order_commodity_type
     *
     * @mbggenerated
     */
    public void setOrder_commodity_type(Integer order_commodity_type) {
        this.order_commodity_type = order_commodity_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.order_commodity_remark
     *
     * @return the value of order_commodity.order_commodity_remark
     *
     * @mbggenerated
     */
    public String getOrder_commodity_remark() {
        return order_commodity_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.order_commodity_remark
     *
     * @param order_commodity_remark the value for order_commodity.order_commodity_remark
     *
     * @mbggenerated
     */
    public void setOrder_commodity_remark(String order_commodity_remark) {
        this.order_commodity_remark = order_commodity_remark == null ? null : order_commodity_remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.revision_size
     *
     * @return the value of order_commodity.revision_size
     *
     * @mbggenerated
     */
    public String getRevision_size() {
        return revision_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.revision_size
     *
     * @param revision_size the value for order_commodity.revision_size
     *
     * @mbggenerated
     */
    public void setRevision_size(String revision_size) {
        this.revision_size = revision_size == null ? null : revision_size.trim();
    }
}