package com.xinshan.model;

import java.math.BigDecimal;

public class OrderCarryFee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_carry_fee.order_carry_fee_id
     *
     * @mbggenerated
     */
    private Integer order_carry_fee_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_carry_fee.order_carry_fee
     *
     * @mbggenerated
     */
    private BigDecimal order_carry_fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_carry_fee.order_id
     *
     * @mbggenerated
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_carry_fee.order_return_id
     *
     * @mbggenerated
     */
    private Integer order_return_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_carry_fee.carry_fee_type
     *
     * @mbggenerated
     */
    private Integer carry_fee_type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_carry_fee.order_carry_fee_id
     *
     * @return the value of order_carry_fee.order_carry_fee_id
     *
     * @mbggenerated
     */
    public Integer getOrder_carry_fee_id() {
        return order_carry_fee_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_carry_fee.order_carry_fee_id
     *
     * @param order_carry_fee_id the value for order_carry_fee.order_carry_fee_id
     *
     * @mbggenerated
     */
    public void setOrder_carry_fee_id(Integer order_carry_fee_id) {
        this.order_carry_fee_id = order_carry_fee_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_carry_fee.order_carry_fee
     *
     * @return the value of order_carry_fee.order_carry_fee
     *
     * @mbggenerated
     */
    public BigDecimal getOrder_carry_fee() {
        return order_carry_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_carry_fee.order_carry_fee
     *
     * @param order_carry_fee the value for order_carry_fee.order_carry_fee
     *
     * @mbggenerated
     */
    public void setOrder_carry_fee(BigDecimal order_carry_fee) {
        this.order_carry_fee = order_carry_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_carry_fee.order_id
     *
     * @return the value of order_carry_fee.order_id
     *
     * @mbggenerated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_carry_fee.order_id
     *
     * @param order_id the value for order_carry_fee.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_carry_fee.order_return_id
     *
     * @return the value of order_carry_fee.order_return_id
     *
     * @mbggenerated
     */
    public Integer getOrder_return_id() {
        return order_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_carry_fee.order_return_id
     *
     * @param order_return_id the value for order_carry_fee.order_return_id
     *
     * @mbggenerated
     */
    public void setOrder_return_id(Integer order_return_id) {
        this.order_return_id = order_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_carry_fee.carry_fee_type
     *
     * @return the value of order_carry_fee.carry_fee_type
     *
     * @mbggenerated
     */
    public Integer getCarry_fee_type() {
        return carry_fee_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_carry_fee.carry_fee_type
     *
     * @param carry_fee_type the value for order_carry_fee.carry_fee_type
     *
     * @mbggenerated
     */
    public void setCarry_fee_type(Integer carry_fee_type) {
        this.carry_fee_type = carry_fee_type;
    }
}