package com.xinshan.model;

public class OrderClause {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_clause.order_clause_id
     *
     * @mbggenerated
     */
    private Integer order_clause_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_clause.order_clause_type
     *
     * @mbggenerated
     */
    private Integer order_clause_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_clause.order_clause
     *
     * @mbggenerated
     */
    private String order_clause;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_clause.order_clause_id
     *
     * @return the value of order_clause.order_clause_id
     *
     * @mbggenerated
     */
    public Integer getOrder_clause_id() {
        return order_clause_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_clause.order_clause_id
     *
     * @param order_clause_id the value for order_clause.order_clause_id
     *
     * @mbggenerated
     */
    public void setOrder_clause_id(Integer order_clause_id) {
        this.order_clause_id = order_clause_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_clause.order_clause_type
     *
     * @return the value of order_clause.order_clause_type
     *
     * @mbggenerated
     */
    public Integer getOrder_clause_type() {
        return order_clause_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_clause.order_clause_type
     *
     * @param order_clause_type the value for order_clause.order_clause_type
     *
     * @mbggenerated
     */
    public void setOrder_clause_type(Integer order_clause_type) {
        this.order_clause_type = order_clause_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_clause.order_clause
     *
     * @return the value of order_clause.order_clause
     *
     * @mbggenerated
     */
    public String getOrder_clause() {
        return order_clause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_clause.order_clause
     *
     * @param order_clause the value for order_clause.order_clause
     *
     * @mbggenerated
     */
    public void setOrder_clause(String order_clause) {
        this.order_clause = order_clause == null ? null : order_clause.trim();
    }
}