package com.xinshan.model;

import java.util.Date;

public class OrderCommodityReturn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_return.order_commodity_return_id
     *
     * @mbggenerated
     */
    private Integer order_commodity_return_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_return.order_id
     *
     * @mbggenerated
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_return.order_commodity_ids
     *
     * @mbggenerated
     */
    private String order_commodity_ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_return.order_commodity_return_date
     *
     * @mbggenerated
     */
    private Date order_commodity_return_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_return.return_employee_code
     *
     * @mbggenerated
     */
    private String return_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_return.return_employee_name
     *
     * @mbggenerated
     */
    private String return_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_return.return_reason
     *
     * @mbggenerated
     */
    private String return_reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_return.return_num
     *
     * @mbggenerated
     */
    private Integer return_num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_return.order_commodity_return_id
     *
     * @return the value of order_commodity_return.order_commodity_return_id
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_return_id() {
        return order_commodity_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_return.order_commodity_return_id
     *
     * @param order_commodity_return_id the value for order_commodity_return.order_commodity_return_id
     *
     * @mbggenerated
     */
    public void setOrder_commodity_return_id(Integer order_commodity_return_id) {
        this.order_commodity_return_id = order_commodity_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_return.order_id
     *
     * @return the value of order_commodity_return.order_id
     *
     * @mbggenerated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_return.order_id
     *
     * @param order_id the value for order_commodity_return.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_return.order_commodity_ids
     *
     * @return the value of order_commodity_return.order_commodity_ids
     *
     * @mbggenerated
     */
    public String getOrder_commodity_ids() {
        return order_commodity_ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_return.order_commodity_ids
     *
     * @param order_commodity_ids the value for order_commodity_return.order_commodity_ids
     *
     * @mbggenerated
     */
    public void setOrder_commodity_ids(String order_commodity_ids) {
        this.order_commodity_ids = order_commodity_ids == null ? null : order_commodity_ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_return.order_commodity_return_date
     *
     * @return the value of order_commodity_return.order_commodity_return_date
     *
     * @mbggenerated
     */
    public Date getOrder_commodity_return_date() {
        return order_commodity_return_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_return.order_commodity_return_date
     *
     * @param order_commodity_return_date the value for order_commodity_return.order_commodity_return_date
     *
     * @mbggenerated
     */
    public void setOrder_commodity_return_date(Date order_commodity_return_date) {
        this.order_commodity_return_date = order_commodity_return_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_return.return_employee_code
     *
     * @return the value of order_commodity_return.return_employee_code
     *
     * @mbggenerated
     */
    public String getReturn_employee_code() {
        return return_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_return.return_employee_code
     *
     * @param return_employee_code the value for order_commodity_return.return_employee_code
     *
     * @mbggenerated
     */
    public void setReturn_employee_code(String return_employee_code) {
        this.return_employee_code = return_employee_code == null ? null : return_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_return.return_employee_name
     *
     * @return the value of order_commodity_return.return_employee_name
     *
     * @mbggenerated
     */
    public String getReturn_employee_name() {
        return return_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_return.return_employee_name
     *
     * @param return_employee_name the value for order_commodity_return.return_employee_name
     *
     * @mbggenerated
     */
    public void setReturn_employee_name(String return_employee_name) {
        this.return_employee_name = return_employee_name == null ? null : return_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_return.return_reason
     *
     * @return the value of order_commodity_return.return_reason
     *
     * @mbggenerated
     */
    public String getReturn_reason() {
        return return_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_return.return_reason
     *
     * @param return_reason the value for order_commodity_return.return_reason
     *
     * @mbggenerated
     */
    public void setReturn_reason(String return_reason) {
        this.return_reason = return_reason == null ? null : return_reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_return.return_num
     *
     * @return the value of order_commodity_return.return_num
     *
     * @mbggenerated
     */
    public Integer getReturn_num() {
        return return_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_return.return_num
     *
     * @param return_num the value for order_commodity_return.return_num
     *
     * @mbggenerated
     */
    public void setReturn_num(Integer return_num) {
        this.return_num = return_num;
    }
}