package com.xinshan.model;

import java.util.Date;

public class OrderCommoditySupplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_supplier.order_commodity_supplier_id
     *
     * @mbggenerated
     */
    private Integer order_commodity_supplier_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_supplier.order_commodity_id
     *
     * @mbggenerated
     */
    private Integer order_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_supplier.order_commodity_supplier_status
     *
     * @mbggenerated
     */
    private Integer order_commodity_supplier_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_supplier.supplier_confirm_employee_code
     *
     * @mbggenerated
     */
    private String supplier_confirm_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_supplier.supplier_confirm_employee_name
     *
     * @mbggenerated
     */
    private String supplier_confirm_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_supplier.supplier_confirm_date
     *
     * @mbggenerated
     */
    private Date supplier_confirm_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_supplier.supplier_arrival_employee_code
     *
     * @mbggenerated
     */
    private String supplier_arrival_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_supplier.supplier_arrival_employee_name
     *
     * @mbggenerated
     */
    private String supplier_arrival_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_supplier.supplier_arrival_date
     *
     * @mbggenerated
     */
    private Date supplier_arrival_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_supplier.order_commodity_supplier_id
     *
     * @return the value of order_commodity_supplier.order_commodity_supplier_id
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_supplier_id() {
        return order_commodity_supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_supplier.order_commodity_supplier_id
     *
     * @param order_commodity_supplier_id the value for order_commodity_supplier.order_commodity_supplier_id
     *
     * @mbggenerated
     */
    public void setOrder_commodity_supplier_id(Integer order_commodity_supplier_id) {
        this.order_commodity_supplier_id = order_commodity_supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_supplier.order_commodity_id
     *
     * @return the value of order_commodity_supplier.order_commodity_id
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_id() {
        return order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_supplier.order_commodity_id
     *
     * @param order_commodity_id the value for order_commodity_supplier.order_commodity_id
     *
     * @mbggenerated
     */
    public void setOrder_commodity_id(Integer order_commodity_id) {
        this.order_commodity_id = order_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_supplier.order_commodity_supplier_status
     *
     * @return the value of order_commodity_supplier.order_commodity_supplier_status
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_supplier_status() {
        return order_commodity_supplier_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_supplier.order_commodity_supplier_status
     *
     * @param order_commodity_supplier_status the value for order_commodity_supplier.order_commodity_supplier_status
     *
     * @mbggenerated
     */
    public void setOrder_commodity_supplier_status(Integer order_commodity_supplier_status) {
        this.order_commodity_supplier_status = order_commodity_supplier_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_supplier.supplier_confirm_employee_code
     *
     * @return the value of order_commodity_supplier.supplier_confirm_employee_code
     *
     * @mbggenerated
     */
    public String getSupplier_confirm_employee_code() {
        return supplier_confirm_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_supplier.supplier_confirm_employee_code
     *
     * @param supplier_confirm_employee_code the value for order_commodity_supplier.supplier_confirm_employee_code
     *
     * @mbggenerated
     */
    public void setSupplier_confirm_employee_code(String supplier_confirm_employee_code) {
        this.supplier_confirm_employee_code = supplier_confirm_employee_code == null ? null : supplier_confirm_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_supplier.supplier_confirm_employee_name
     *
     * @return the value of order_commodity_supplier.supplier_confirm_employee_name
     *
     * @mbggenerated
     */
    public String getSupplier_confirm_employee_name() {
        return supplier_confirm_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_supplier.supplier_confirm_employee_name
     *
     * @param supplier_confirm_employee_name the value for order_commodity_supplier.supplier_confirm_employee_name
     *
     * @mbggenerated
     */
    public void setSupplier_confirm_employee_name(String supplier_confirm_employee_name) {
        this.supplier_confirm_employee_name = supplier_confirm_employee_name == null ? null : supplier_confirm_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_supplier.supplier_confirm_date
     *
     * @return the value of order_commodity_supplier.supplier_confirm_date
     *
     * @mbggenerated
     */
    public Date getSupplier_confirm_date() {
        return supplier_confirm_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_supplier.supplier_confirm_date
     *
     * @param supplier_confirm_date the value for order_commodity_supplier.supplier_confirm_date
     *
     * @mbggenerated
     */
    public void setSupplier_confirm_date(Date supplier_confirm_date) {
        this.supplier_confirm_date = supplier_confirm_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_supplier.supplier_arrival_employee_code
     *
     * @return the value of order_commodity_supplier.supplier_arrival_employee_code
     *
     * @mbggenerated
     */
    public String getSupplier_arrival_employee_code() {
        return supplier_arrival_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_supplier.supplier_arrival_employee_code
     *
     * @param supplier_arrival_employee_code the value for order_commodity_supplier.supplier_arrival_employee_code
     *
     * @mbggenerated
     */
    public void setSupplier_arrival_employee_code(String supplier_arrival_employee_code) {
        this.supplier_arrival_employee_code = supplier_arrival_employee_code == null ? null : supplier_arrival_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_supplier.supplier_arrival_employee_name
     *
     * @return the value of order_commodity_supplier.supplier_arrival_employee_name
     *
     * @mbggenerated
     */
    public String getSupplier_arrival_employee_name() {
        return supplier_arrival_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_supplier.supplier_arrival_employee_name
     *
     * @param supplier_arrival_employee_name the value for order_commodity_supplier.supplier_arrival_employee_name
     *
     * @mbggenerated
     */
    public void setSupplier_arrival_employee_name(String supplier_arrival_employee_name) {
        this.supplier_arrival_employee_name = supplier_arrival_employee_name == null ? null : supplier_arrival_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_supplier.supplier_arrival_date
     *
     * @return the value of order_commodity_supplier.supplier_arrival_date
     *
     * @mbggenerated
     */
    public Date getSupplier_arrival_date() {
        return supplier_arrival_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_supplier.supplier_arrival_date
     *
     * @param supplier_arrival_date the value for order_commodity_supplier.supplier_arrival_date
     *
     * @mbggenerated
     */
    public void setSupplier_arrival_date(Date supplier_arrival_date) {
        this.supplier_arrival_date = supplier_arrival_date;
    }
}