package com.xinshan.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderPay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_pay_id
     *
     * @mbggenerated
     */
    private Integer order_pay_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_id
     *
     * @mbggenerated
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.need_amount
     *
     * @mbggenerated
     */
    private BigDecimal need_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_amount
     *
     * @mbggenerated
     */
    private BigDecimal pay_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_date
     *
     * @mbggenerated
     */
    private Date pay_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.cashier_employee_code
     *
     * @mbggenerated
     */
    private String cashier_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.cashier_employee_name
     *
     * @mbggenerated
     */
    private String cashier_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_source
     *
     * @mbggenerated
     */
    private Integer pay_source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.position_id
     *
     * @mbggenerated
     */
    private Integer position_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_return_id
     *
     * @mbggenerated
     */
    private Integer order_return_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_pay_type
     *
     * @mbggenerated
     */
    private Integer order_pay_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_return
     *
     * @mbggenerated
     */
    private Integer pay_return;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.daogou_position_id
     *
     * @mbggenerated
     */
    private Integer daogou_position_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.daogou_employee_code
     *
     * @mbggenerated
     */
    private String daogou_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.daogou_employee_name
     *
     * @mbggenerated
     */
    private String daogou_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_pay_remark
     *
     * @mbggenerated
     */
    private String order_pay_remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_pay_id
     *
     * @return the value of order_pay.order_pay_id
     *
     * @mbggenerated
     */
    public Integer getOrder_pay_id() {
        return order_pay_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_pay_id
     *
     * @param order_pay_id the value for order_pay.order_pay_id
     *
     * @mbggenerated
     */
    public void setOrder_pay_id(Integer order_pay_id) {
        this.order_pay_id = order_pay_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_id
     *
     * @return the value of order_pay.order_id
     *
     * @mbggenerated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_id
     *
     * @param order_id the value for order_pay.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.need_amount
     *
     * @return the value of order_pay.need_amount
     *
     * @mbggenerated
     */
    public BigDecimal getNeed_amount() {
        return need_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.need_amount
     *
     * @param need_amount the value for order_pay.need_amount
     *
     * @mbggenerated
     */
    public void setNeed_amount(BigDecimal need_amount) {
        this.need_amount = need_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_amount
     *
     * @return the value of order_pay.pay_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPay_amount() {
        return pay_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_amount
     *
     * @param pay_amount the value for order_pay.pay_amount
     *
     * @mbggenerated
     */
    public void setPay_amount(BigDecimal pay_amount) {
        this.pay_amount = pay_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_date
     *
     * @return the value of order_pay.pay_date
     *
     * @mbggenerated
     */
    public Date getPay_date() {
        return pay_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_date
     *
     * @param pay_date the value for order_pay.pay_date
     *
     * @mbggenerated
     */
    public void setPay_date(Date pay_date) {
        this.pay_date = pay_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.cashier_employee_code
     *
     * @return the value of order_pay.cashier_employee_code
     *
     * @mbggenerated
     */
    public String getCashier_employee_code() {
        return cashier_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.cashier_employee_code
     *
     * @param cashier_employee_code the value for order_pay.cashier_employee_code
     *
     * @mbggenerated
     */
    public void setCashier_employee_code(String cashier_employee_code) {
        this.cashier_employee_code = cashier_employee_code == null ? null : cashier_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.cashier_employee_name
     *
     * @return the value of order_pay.cashier_employee_name
     *
     * @mbggenerated
     */
    public String getCashier_employee_name() {
        return cashier_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.cashier_employee_name
     *
     * @param cashier_employee_name the value for order_pay.cashier_employee_name
     *
     * @mbggenerated
     */
    public void setCashier_employee_name(String cashier_employee_name) {
        this.cashier_employee_name = cashier_employee_name == null ? null : cashier_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_source
     *
     * @return the value of order_pay.pay_source
     *
     * @mbggenerated
     */
    public Integer getPay_source() {
        return pay_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_source
     *
     * @param pay_source the value for order_pay.pay_source
     *
     * @mbggenerated
     */
    public void setPay_source(Integer pay_source) {
        this.pay_source = pay_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.position_id
     *
     * @return the value of order_pay.position_id
     *
     * @mbggenerated
     */
    public Integer getPosition_id() {
        return position_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.position_id
     *
     * @param position_id the value for order_pay.position_id
     *
     * @mbggenerated
     */
    public void setPosition_id(Integer position_id) {
        this.position_id = position_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_return_id
     *
     * @return the value of order_pay.order_return_id
     *
     * @mbggenerated
     */
    public Integer getOrder_return_id() {
        return order_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_return_id
     *
     * @param order_return_id the value for order_pay.order_return_id
     *
     * @mbggenerated
     */
    public void setOrder_return_id(Integer order_return_id) {
        this.order_return_id = order_return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_pay_type
     *
     * @return the value of order_pay.order_pay_type
     *
     * @mbggenerated
     */
    public Integer getOrder_pay_type() {
        return order_pay_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_pay_type
     *
     * @param order_pay_type the value for order_pay.order_pay_type
     *
     * @mbggenerated
     */
    public void setOrder_pay_type(Integer order_pay_type) {
        this.order_pay_type = order_pay_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_return
     *
     * @return the value of order_pay.pay_return
     *
     * @mbggenerated
     */
    public Integer getPay_return() {
        return pay_return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_return
     *
     * @param pay_return the value for order_pay.pay_return
     *
     * @mbggenerated
     */
    public void setPay_return(Integer pay_return) {
        this.pay_return = pay_return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.daogou_position_id
     *
     * @return the value of order_pay.daogou_position_id
     *
     * @mbggenerated
     */
    public Integer getDaogou_position_id() {
        return daogou_position_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.daogou_position_id
     *
     * @param daogou_position_id the value for order_pay.daogou_position_id
     *
     * @mbggenerated
     */
    public void setDaogou_position_id(Integer daogou_position_id) {
        this.daogou_position_id = daogou_position_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.daogou_employee_code
     *
     * @return the value of order_pay.daogou_employee_code
     *
     * @mbggenerated
     */
    public String getDaogou_employee_code() {
        return daogou_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.daogou_employee_code
     *
     * @param daogou_employee_code the value for order_pay.daogou_employee_code
     *
     * @mbggenerated
     */
    public void setDaogou_employee_code(String daogou_employee_code) {
        this.daogou_employee_code = daogou_employee_code == null ? null : daogou_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.daogou_employee_name
     *
     * @return the value of order_pay.daogou_employee_name
     *
     * @mbggenerated
     */
    public String getDaogou_employee_name() {
        return daogou_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.daogou_employee_name
     *
     * @param daogou_employee_name the value for order_pay.daogou_employee_name
     *
     * @mbggenerated
     */
    public void setDaogou_employee_name(String daogou_employee_name) {
        this.daogou_employee_name = daogou_employee_name == null ? null : daogou_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_pay_remark
     *
     * @return the value of order_pay.order_pay_remark
     *
     * @mbggenerated
     */
    public String getOrder_pay_remark() {
        return order_pay_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_pay_remark
     *
     * @param order_pay_remark the value for order_pay.order_pay_remark
     *
     * @mbggenerated
     */
    public void setOrder_pay_remark(String order_pay_remark) {
        this.order_pay_remark = order_pay_remark == null ? null : order_pay_remark.trim();
    }
}