package com.xinshan.model;

import java.util.Date;

public class PurchaseCommodityArrival {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_commodity_arrival.purchase_commodity_arrival_id
     *
     * @mbggenerated
     */
    private Integer purchase_commodity_arrival_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_commodity_arrival.purchase_commodity_id
     *
     * @mbggenerated
     */
    private Integer purchase_commodity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_commodity_arrival.purchase_commodity_arrival_date
     *
     * @mbggenerated
     */
    private Date purchase_commodity_arrival_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_commodity_arrival.arrival_employee_code
     *
     * @mbggenerated
     */
    private String arrival_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_commodity_arrival.arrival_employee_name
     *
     * @mbggenerated
     */
    private String arrival_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_commodity_arrival.purchase_commodity_arrival_num
     *
     * @mbggenerated
     */
    private Integer purchase_commodity_arrival_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_commodity_arrival.purchase_commodity_arrival_remark
     *
     * @mbggenerated
     */
    private String purchase_commodity_arrival_remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_commodity_arrival.purchase_commodity_arrival_id
     *
     * @return the value of purchase_commodity_arrival.purchase_commodity_arrival_id
     *
     * @mbggenerated
     */
    public Integer getPurchase_commodity_arrival_id() {
        return purchase_commodity_arrival_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_commodity_arrival.purchase_commodity_arrival_id
     *
     * @param purchase_commodity_arrival_id the value for purchase_commodity_arrival.purchase_commodity_arrival_id
     *
     * @mbggenerated
     */
    public void setPurchase_commodity_arrival_id(Integer purchase_commodity_arrival_id) {
        this.purchase_commodity_arrival_id = purchase_commodity_arrival_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_commodity_arrival.purchase_commodity_id
     *
     * @return the value of purchase_commodity_arrival.purchase_commodity_id
     *
     * @mbggenerated
     */
    public Integer getPurchase_commodity_id() {
        return purchase_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_commodity_arrival.purchase_commodity_id
     *
     * @param purchase_commodity_id the value for purchase_commodity_arrival.purchase_commodity_id
     *
     * @mbggenerated
     */
    public void setPurchase_commodity_id(Integer purchase_commodity_id) {
        this.purchase_commodity_id = purchase_commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_commodity_arrival.purchase_commodity_arrival_date
     *
     * @return the value of purchase_commodity_arrival.purchase_commodity_arrival_date
     *
     * @mbggenerated
     */
    public Date getPurchase_commodity_arrival_date() {
        return purchase_commodity_arrival_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_commodity_arrival.purchase_commodity_arrival_date
     *
     * @param purchase_commodity_arrival_date the value for purchase_commodity_arrival.purchase_commodity_arrival_date
     *
     * @mbggenerated
     */
    public void setPurchase_commodity_arrival_date(Date purchase_commodity_arrival_date) {
        this.purchase_commodity_arrival_date = purchase_commodity_arrival_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_commodity_arrival.arrival_employee_code
     *
     * @return the value of purchase_commodity_arrival.arrival_employee_code
     *
     * @mbggenerated
     */
    public String getArrival_employee_code() {
        return arrival_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_commodity_arrival.arrival_employee_code
     *
     * @param arrival_employee_code the value for purchase_commodity_arrival.arrival_employee_code
     *
     * @mbggenerated
     */
    public void setArrival_employee_code(String arrival_employee_code) {
        this.arrival_employee_code = arrival_employee_code == null ? null : arrival_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_commodity_arrival.arrival_employee_name
     *
     * @return the value of purchase_commodity_arrival.arrival_employee_name
     *
     * @mbggenerated
     */
    public String getArrival_employee_name() {
        return arrival_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_commodity_arrival.arrival_employee_name
     *
     * @param arrival_employee_name the value for purchase_commodity_arrival.arrival_employee_name
     *
     * @mbggenerated
     */
    public void setArrival_employee_name(String arrival_employee_name) {
        this.arrival_employee_name = arrival_employee_name == null ? null : arrival_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_commodity_arrival.purchase_commodity_arrival_num
     *
     * @return the value of purchase_commodity_arrival.purchase_commodity_arrival_num
     *
     * @mbggenerated
     */
    public Integer getPurchase_commodity_arrival_num() {
        return purchase_commodity_arrival_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_commodity_arrival.purchase_commodity_arrival_num
     *
     * @param purchase_commodity_arrival_num the value for purchase_commodity_arrival.purchase_commodity_arrival_num
     *
     * @mbggenerated
     */
    public void setPurchase_commodity_arrival_num(Integer purchase_commodity_arrival_num) {
        this.purchase_commodity_arrival_num = purchase_commodity_arrival_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_commodity_arrival.purchase_commodity_arrival_remark
     *
     * @return the value of purchase_commodity_arrival.purchase_commodity_arrival_remark
     *
     * @mbggenerated
     */
    public String getPurchase_commodity_arrival_remark() {
        return purchase_commodity_arrival_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_commodity_arrival.purchase_commodity_arrival_remark
     *
     * @param purchase_commodity_arrival_remark the value for purchase_commodity_arrival.purchase_commodity_arrival_remark
     *
     * @mbggenerated
     */
    public void setPurchase_commodity_arrival_remark(String purchase_commodity_arrival_remark) {
        this.purchase_commodity_arrival_remark = purchase_commodity_arrival_remark == null ? null : purchase_commodity_arrival_remark.trim();
    }
}