package com.xinshan.model;

import java.math.BigDecimal;

public class SalesTargetAnalysis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_target_analysis.sales_target_analysis_id
     *
     * @mbggenerated
     */
    private Integer sales_target_analysis_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_target_analysis.sales_target_id
     *
     * @mbggenerated
     */
    private Integer sales_target_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_target_analysis.sales_target_amount_id
     *
     * @mbggenerated
     */
    private Integer sales_target_amount_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_target_analysis.sales_amount
     *
     * @mbggenerated
     */
    private BigDecimal sales_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_target_analysis.sales_add_up_amount
     *
     * @mbggenerated
     */
    private BigDecimal sales_add_up_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_target_analysis.sales_add_up_target
     *
     * @mbggenerated
     */
    private BigDecimal sales_add_up_target;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_target_analysis.sales_target_analysis_id
     *
     * @return the value of sales_target_analysis.sales_target_analysis_id
     *
     * @mbggenerated
     */
    public Integer getSales_target_analysis_id() {
        return sales_target_analysis_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_target_analysis.sales_target_analysis_id
     *
     * @param sales_target_analysis_id the value for sales_target_analysis.sales_target_analysis_id
     *
     * @mbggenerated
     */
    public void setSales_target_analysis_id(Integer sales_target_analysis_id) {
        this.sales_target_analysis_id = sales_target_analysis_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_target_analysis.sales_target_id
     *
     * @return the value of sales_target_analysis.sales_target_id
     *
     * @mbggenerated
     */
    public Integer getSales_target_id() {
        return sales_target_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_target_analysis.sales_target_id
     *
     * @param sales_target_id the value for sales_target_analysis.sales_target_id
     *
     * @mbggenerated
     */
    public void setSales_target_id(Integer sales_target_id) {
        this.sales_target_id = sales_target_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_target_analysis.sales_target_amount_id
     *
     * @return the value of sales_target_analysis.sales_target_amount_id
     *
     * @mbggenerated
     */
    public Integer getSales_target_amount_id() {
        return sales_target_amount_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_target_analysis.sales_target_amount_id
     *
     * @param sales_target_amount_id the value for sales_target_analysis.sales_target_amount_id
     *
     * @mbggenerated
     */
    public void setSales_target_amount_id(Integer sales_target_amount_id) {
        this.sales_target_amount_id = sales_target_amount_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_target_analysis.sales_amount
     *
     * @return the value of sales_target_analysis.sales_amount
     *
     * @mbggenerated
     */
    public BigDecimal getSales_amount() {
        return sales_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_target_analysis.sales_amount
     *
     * @param sales_amount the value for sales_target_analysis.sales_amount
     *
     * @mbggenerated
     */
    public void setSales_amount(BigDecimal sales_amount) {
        this.sales_amount = sales_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_target_analysis.sales_add_up_amount
     *
     * @return the value of sales_target_analysis.sales_add_up_amount
     *
     * @mbggenerated
     */
    public BigDecimal getSales_add_up_amount() {
        return sales_add_up_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_target_analysis.sales_add_up_amount
     *
     * @param sales_add_up_amount the value for sales_target_analysis.sales_add_up_amount
     *
     * @mbggenerated
     */
    public void setSales_add_up_amount(BigDecimal sales_add_up_amount) {
        this.sales_add_up_amount = sales_add_up_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_target_analysis.sales_add_up_target
     *
     * @return the value of sales_target_analysis.sales_add_up_target
     *
     * @mbggenerated
     */
    public BigDecimal getSales_add_up_target() {
        return sales_add_up_target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_target_analysis.sales_add_up_target
     *
     * @param sales_add_up_target the value for sales_target_analysis.sales_add_up_target
     *
     * @mbggenerated
     */
    public void setSales_add_up_target(BigDecimal sales_add_up_target) {
        this.sales_add_up_target = sales_add_up_target;
    }
}