package com.xinshan.model;

import java.math.BigDecimal;

public class SalesContacts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.sales_contacts_id
     *
     * @mbggenerated
     */
    private Integer sales_contacts_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.contacts
     *
     * @mbggenerated
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.month
     *
     * @mbggenerated
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.sales_amount
     *
     * @mbggenerated
     */
    private BigDecimal sales_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.cost_amount
     *
     * @mbggenerated
     */
    private BigDecimal cost_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.sales_num
     *
     * @mbggenerated
     */
    private Integer sales_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.add_up_amount
     *
     * @mbggenerated
     */
    private BigDecimal add_up_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.add_up_cost_amount
     *
     * @mbggenerated
     */
    private BigDecimal add_up_cost_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.add_up_num
     *
     * @mbggenerated
     */
    private Integer add_up_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.return_commodity_amount
     *
     * @mbggenerated
     */
    private BigDecimal return_commodity_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.return_commodity_cost
     *
     * @mbggenerated
     */
    private BigDecimal return_commodity_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.return_commodity_num
     *
     * @mbggenerated
     */
    private Integer return_commodity_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.return_add_commodity_amount
     *
     * @mbggenerated
     */
    private BigDecimal return_add_commodity_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.return_add_commodity_cost
     *
     * @mbggenerated
     */
    private BigDecimal return_add_commodity_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.return_add_commodity_num
     *
     * @mbggenerated
     */
    private Integer return_add_commodity_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.order_commodity_amount
     *
     * @mbggenerated
     */
    private BigDecimal order_commodity_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.order_commodity_cost
     *
     * @mbggenerated
     */
    private BigDecimal order_commodity_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_contacts.order_commodity_num
     *
     * @mbggenerated
     */
    private Integer order_commodity_num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.sales_contacts_id
     *
     * @return the value of sales_contacts.sales_contacts_id
     *
     * @mbggenerated
     */
    public Integer getSales_contacts_id() {
        return sales_contacts_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.sales_contacts_id
     *
     * @param sales_contacts_id the value for sales_contacts.sales_contacts_id
     *
     * @mbggenerated
     */
    public void setSales_contacts_id(Integer sales_contacts_id) {
        this.sales_contacts_id = sales_contacts_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.contacts
     *
     * @return the value of sales_contacts.contacts
     *
     * @mbggenerated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.contacts
     *
     * @param contacts the value for sales_contacts.contacts
     *
     * @mbggenerated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.month
     *
     * @return the value of sales_contacts.month
     *
     * @mbggenerated
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.month
     *
     * @param month the value for sales_contacts.month
     *
     * @mbggenerated
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.sales_amount
     *
     * @return the value of sales_contacts.sales_amount
     *
     * @mbggenerated
     */
    public BigDecimal getSales_amount() {
        return sales_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.sales_amount
     *
     * @param sales_amount the value for sales_contacts.sales_amount
     *
     * @mbggenerated
     */
    public void setSales_amount(BigDecimal sales_amount) {
        this.sales_amount = sales_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.cost_amount
     *
     * @return the value of sales_contacts.cost_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCost_amount() {
        return cost_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.cost_amount
     *
     * @param cost_amount the value for sales_contacts.cost_amount
     *
     * @mbggenerated
     */
    public void setCost_amount(BigDecimal cost_amount) {
        this.cost_amount = cost_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.sales_num
     *
     * @return the value of sales_contacts.sales_num
     *
     * @mbggenerated
     */
    public Integer getSales_num() {
        return sales_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.sales_num
     *
     * @param sales_num the value for sales_contacts.sales_num
     *
     * @mbggenerated
     */
    public void setSales_num(Integer sales_num) {
        this.sales_num = sales_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.add_up_amount
     *
     * @return the value of sales_contacts.add_up_amount
     *
     * @mbggenerated
     */
    public BigDecimal getAdd_up_amount() {
        return add_up_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.add_up_amount
     *
     * @param add_up_amount the value for sales_contacts.add_up_amount
     *
     * @mbggenerated
     */
    public void setAdd_up_amount(BigDecimal add_up_amount) {
        this.add_up_amount = add_up_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.add_up_cost_amount
     *
     * @return the value of sales_contacts.add_up_cost_amount
     *
     * @mbggenerated
     */
    public BigDecimal getAdd_up_cost_amount() {
        return add_up_cost_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.add_up_cost_amount
     *
     * @param add_up_cost_amount the value for sales_contacts.add_up_cost_amount
     *
     * @mbggenerated
     */
    public void setAdd_up_cost_amount(BigDecimal add_up_cost_amount) {
        this.add_up_cost_amount = add_up_cost_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.add_up_num
     *
     * @return the value of sales_contacts.add_up_num
     *
     * @mbggenerated
     */
    public Integer getAdd_up_num() {
        return add_up_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.add_up_num
     *
     * @param add_up_num the value for sales_contacts.add_up_num
     *
     * @mbggenerated
     */
    public void setAdd_up_num(Integer add_up_num) {
        this.add_up_num = add_up_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.return_commodity_amount
     *
     * @return the value of sales_contacts.return_commodity_amount
     *
     * @mbggenerated
     */
    public BigDecimal getReturn_commodity_amount() {
        return return_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.return_commodity_amount
     *
     * @param return_commodity_amount the value for sales_contacts.return_commodity_amount
     *
     * @mbggenerated
     */
    public void setReturn_commodity_amount(BigDecimal return_commodity_amount) {
        this.return_commodity_amount = return_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.return_commodity_cost
     *
     * @return the value of sales_contacts.return_commodity_cost
     *
     * @mbggenerated
     */
    public BigDecimal getReturn_commodity_cost() {
        return return_commodity_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.return_commodity_cost
     *
     * @param return_commodity_cost the value for sales_contacts.return_commodity_cost
     *
     * @mbggenerated
     */
    public void setReturn_commodity_cost(BigDecimal return_commodity_cost) {
        this.return_commodity_cost = return_commodity_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.return_commodity_num
     *
     * @return the value of sales_contacts.return_commodity_num
     *
     * @mbggenerated
     */
    public Integer getReturn_commodity_num() {
        return return_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.return_commodity_num
     *
     * @param return_commodity_num the value for sales_contacts.return_commodity_num
     *
     * @mbggenerated
     */
    public void setReturn_commodity_num(Integer return_commodity_num) {
        this.return_commodity_num = return_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.return_add_commodity_amount
     *
     * @return the value of sales_contacts.return_add_commodity_amount
     *
     * @mbggenerated
     */
    public BigDecimal getReturn_add_commodity_amount() {
        return return_add_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.return_add_commodity_amount
     *
     * @param return_add_commodity_amount the value for sales_contacts.return_add_commodity_amount
     *
     * @mbggenerated
     */
    public void setReturn_add_commodity_amount(BigDecimal return_add_commodity_amount) {
        this.return_add_commodity_amount = return_add_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.return_add_commodity_cost
     *
     * @return the value of sales_contacts.return_add_commodity_cost
     *
     * @mbggenerated
     */
    public BigDecimal getReturn_add_commodity_cost() {
        return return_add_commodity_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.return_add_commodity_cost
     *
     * @param return_add_commodity_cost the value for sales_contacts.return_add_commodity_cost
     *
     * @mbggenerated
     */
    public void setReturn_add_commodity_cost(BigDecimal return_add_commodity_cost) {
        this.return_add_commodity_cost = return_add_commodity_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.return_add_commodity_num
     *
     * @return the value of sales_contacts.return_add_commodity_num
     *
     * @mbggenerated
     */
    public Integer getReturn_add_commodity_num() {
        return return_add_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.return_add_commodity_num
     *
     * @param return_add_commodity_num the value for sales_contacts.return_add_commodity_num
     *
     * @mbggenerated
     */
    public void setReturn_add_commodity_num(Integer return_add_commodity_num) {
        this.return_add_commodity_num = return_add_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.order_commodity_amount
     *
     * @return the value of sales_contacts.order_commodity_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOrder_commodity_amount() {
        return order_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.order_commodity_amount
     *
     * @param order_commodity_amount the value for sales_contacts.order_commodity_amount
     *
     * @mbggenerated
     */
    public void setOrder_commodity_amount(BigDecimal order_commodity_amount) {
        this.order_commodity_amount = order_commodity_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.order_commodity_cost
     *
     * @return the value of sales_contacts.order_commodity_cost
     *
     * @mbggenerated
     */
    public BigDecimal getOrder_commodity_cost() {
        return order_commodity_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.order_commodity_cost
     *
     * @param order_commodity_cost the value for sales_contacts.order_commodity_cost
     *
     * @mbggenerated
     */
    public void setOrder_commodity_cost(BigDecimal order_commodity_cost) {
        this.order_commodity_cost = order_commodity_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_contacts.order_commodity_num
     *
     * @return the value of sales_contacts.order_commodity_num
     *
     * @mbggenerated
     */
    public Integer getOrder_commodity_num() {
        return order_commodity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_contacts.order_commodity_num
     *
     * @param order_commodity_num the value for sales_contacts.order_commodity_num
     *
     * @mbggenerated
     */
    public void setOrder_commodity_num(Integer order_commodity_num) {
        this.order_commodity_num = order_commodity_num;
    }
}