package com.xinshan.model;

public class SellType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_type.sell_type_id
     *
     * @mbggenerated
     */
    private Integer sell_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_type.sell_type_name
     *
     * @mbggenerated
     */
    private String sell_type_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_type.sell_type_id
     *
     * @return the value of sell_type.sell_type_id
     *
     * @mbggenerated
     */
    public Integer getSell_type_id() {
        return sell_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_type.sell_type_id
     *
     * @param sell_type_id the value for sell_type.sell_type_id
     *
     * @mbggenerated
     */
    public void setSell_type_id(Integer sell_type_id) {
        this.sell_type_id = sell_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_type.sell_type_name
     *
     * @return the value of sell_type.sell_type_name
     *
     * @mbggenerated
     */
    public String getSell_type_name() {
        return sell_type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_type.sell_type_name
     *
     * @param sell_type_name the value for sell_type.sell_type_name
     *
     * @mbggenerated
     */
    public void setSell_type_name(String sell_type_name) {
        this.sell_type_name = sell_type_name == null ? null : sell_type_name.trim();
    }
}