package com.xinshan.model;

import java.math.BigDecimal;
import java.util.Date;

public class SettlementHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_history.settlement_history_id
     *
     * @mbggenerated
     */
    private Integer settlement_history_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_history.settlement_id
     *
     * @mbggenerated
     */
    private Integer settlement_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_history.settlement_history_amount
     *
     * @mbggenerated
     */
    private BigDecimal settlement_history_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_history.settlement_employee_code
     *
     * @mbggenerated
     */
    private String settlement_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_history.settlement_employee_name
     *
     * @mbggenerated
     */
    private String settlement_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_history.settlement_date
     *
     * @mbggenerated
     */
    private Date settlement_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_history.settlement_remark
     *
     * @mbggenerated
     */
    private String settlement_remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_history.settlement_history_id
     *
     * @return the value of settlement_history.settlement_history_id
     *
     * @mbggenerated
     */
    public Integer getSettlement_history_id() {
        return settlement_history_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_history.settlement_history_id
     *
     * @param settlement_history_id the value for settlement_history.settlement_history_id
     *
     * @mbggenerated
     */
    public void setSettlement_history_id(Integer settlement_history_id) {
        this.settlement_history_id = settlement_history_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_history.settlement_id
     *
     * @return the value of settlement_history.settlement_id
     *
     * @mbggenerated
     */
    public Integer getSettlement_id() {
        return settlement_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_history.settlement_id
     *
     * @param settlement_id the value for settlement_history.settlement_id
     *
     * @mbggenerated
     */
    public void setSettlement_id(Integer settlement_id) {
        this.settlement_id = settlement_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_history.settlement_history_amount
     *
     * @return the value of settlement_history.settlement_history_amount
     *
     * @mbggenerated
     */
    public BigDecimal getSettlement_history_amount() {
        return settlement_history_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_history.settlement_history_amount
     *
     * @param settlement_history_amount the value for settlement_history.settlement_history_amount
     *
     * @mbggenerated
     */
    public void setSettlement_history_amount(BigDecimal settlement_history_amount) {
        this.settlement_history_amount = settlement_history_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_history.settlement_employee_code
     *
     * @return the value of settlement_history.settlement_employee_code
     *
     * @mbggenerated
     */
    public String getSettlement_employee_code() {
        return settlement_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_history.settlement_employee_code
     *
     * @param settlement_employee_code the value for settlement_history.settlement_employee_code
     *
     * @mbggenerated
     */
    public void setSettlement_employee_code(String settlement_employee_code) {
        this.settlement_employee_code = settlement_employee_code == null ? null : settlement_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_history.settlement_employee_name
     *
     * @return the value of settlement_history.settlement_employee_name
     *
     * @mbggenerated
     */
    public String getSettlement_employee_name() {
        return settlement_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_history.settlement_employee_name
     *
     * @param settlement_employee_name the value for settlement_history.settlement_employee_name
     *
     * @mbggenerated
     */
    public void setSettlement_employee_name(String settlement_employee_name) {
        this.settlement_employee_name = settlement_employee_name == null ? null : settlement_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_history.settlement_date
     *
     * @return the value of settlement_history.settlement_date
     *
     * @mbggenerated
     */
    public Date getSettlement_date() {
        return settlement_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_history.settlement_date
     *
     * @param settlement_date the value for settlement_history.settlement_date
     *
     * @mbggenerated
     */
    public void setSettlement_date(Date settlement_date) {
        this.settlement_date = settlement_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_history.settlement_remark
     *
     * @return the value of settlement_history.settlement_remark
     *
     * @mbggenerated
     */
    public String getSettlement_remark() {
        return settlement_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_history.settlement_remark
     *
     * @param settlement_remark the value for settlement_history.settlement_remark
     *
     * @mbggenerated
     */
    public void setSettlement_remark(String settlement_remark) {
        this.settlement_remark = settlement_remark == null ? null : settlement_remark.trim();
    }
}