package com.xinshan.model;

import java.util.Date;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplier_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_name
     *
     * @mbggenerated
     */
    private String supplier_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.district_zip
     *
     * @mbggenerated
     */
    private String district_zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.province_zip
     *
     * @mbggenerated
     */
    private String province_zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.city_zip
     *
     * @mbggenerated
     */
    private String city_zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contacts_phone_number
     *
     * @mbggenerated
     */
    private String contacts_phone_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contacts
     *
     * @mbggenerated
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contacts_address
     *
     * @mbggenerated
     */
    private String contacts_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_rate
     *
     * @mbggenerated
     */
    private Integer supplier_rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_status
     *
     * @mbggenerated
     */
    private Integer supplier_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sell_type_id
     *
     * @mbggenerated
     */
    private Integer sell_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.record_employee_code
     *
     * @mbggenerated
     */
    private String record_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.record_employee_name
     *
     * @mbggenerated
     */
    private String record_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contacts_code
     *
     * @mbggenerated
     */
    private String contacts_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.edit_employee_code
     *
     * @mbggenerated
     */
    private String edit_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.edit_employee_name
     *
     * @mbggenerated
     */
    private String edit_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.edit_date
     *
     * @mbggenerated
     */
    private Date edit_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_id
     *
     * @return the value of supplier.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplier_id() {
        return supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_id
     *
     * @param supplier_id the value for supplier.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplier_id(Integer supplier_id) {
        this.supplier_id = supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_name
     *
     * @return the value of supplier.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplier_name() {
        return supplier_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_name
     *
     * @param supplier_name the value for supplier.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplier_name(String supplier_name) {
        this.supplier_name = supplier_name == null ? null : supplier_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address
     *
     * @return the value of supplier.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address
     *
     * @param address the value for supplier.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.district_zip
     *
     * @return the value of supplier.district_zip
     *
     * @mbggenerated
     */
    public String getDistrict_zip() {
        return district_zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.district_zip
     *
     * @param district_zip the value for supplier.district_zip
     *
     * @mbggenerated
     */
    public void setDistrict_zip(String district_zip) {
        this.district_zip = district_zip == null ? null : district_zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.province_zip
     *
     * @return the value of supplier.province_zip
     *
     * @mbggenerated
     */
    public String getProvince_zip() {
        return province_zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.province_zip
     *
     * @param province_zip the value for supplier.province_zip
     *
     * @mbggenerated
     */
    public void setProvince_zip(String province_zip) {
        this.province_zip = province_zip == null ? null : province_zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.city_zip
     *
     * @return the value of supplier.city_zip
     *
     * @mbggenerated
     */
    public String getCity_zip() {
        return city_zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.city_zip
     *
     * @param city_zip the value for supplier.city_zip
     *
     * @mbggenerated
     */
    public void setCity_zip(String city_zip) {
        this.city_zip = city_zip == null ? null : city_zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contacts_phone_number
     *
     * @return the value of supplier.contacts_phone_number
     *
     * @mbggenerated
     */
    public String getContacts_phone_number() {
        return contacts_phone_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contacts_phone_number
     *
     * @param contacts_phone_number the value for supplier.contacts_phone_number
     *
     * @mbggenerated
     */
    public void setContacts_phone_number(String contacts_phone_number) {
        this.contacts_phone_number = contacts_phone_number == null ? null : contacts_phone_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contacts
     *
     * @return the value of supplier.contacts
     *
     * @mbggenerated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contacts
     *
     * @param contacts the value for supplier.contacts
     *
     * @mbggenerated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contacts_address
     *
     * @return the value of supplier.contacts_address
     *
     * @mbggenerated
     */
    public String getContacts_address() {
        return contacts_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contacts_address
     *
     * @param contacts_address the value for supplier.contacts_address
     *
     * @mbggenerated
     */
    public void setContacts_address(String contacts_address) {
        this.contacts_address = contacts_address == null ? null : contacts_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_rate
     *
     * @return the value of supplier.supplier_rate
     *
     * @mbggenerated
     */
    public Integer getSupplier_rate() {
        return supplier_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_rate
     *
     * @param supplier_rate the value for supplier.supplier_rate
     *
     * @mbggenerated
     */
    public void setSupplier_rate(Integer supplier_rate) {
        this.supplier_rate = supplier_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_status
     *
     * @return the value of supplier.supplier_status
     *
     * @mbggenerated
     */
    public Integer getSupplier_status() {
        return supplier_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_status
     *
     * @param supplier_status the value for supplier.supplier_status
     *
     * @mbggenerated
     */
    public void setSupplier_status(Integer supplier_status) {
        this.supplier_status = supplier_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sell_type_id
     *
     * @return the value of supplier.sell_type_id
     *
     * @mbggenerated
     */
    public Integer getSell_type_id() {
        return sell_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sell_type_id
     *
     * @param sell_type_id the value for supplier.sell_type_id
     *
     * @mbggenerated
     */
    public void setSell_type_id(Integer sell_type_id) {
        this.sell_type_id = sell_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.record_employee_code
     *
     * @return the value of supplier.record_employee_code
     *
     * @mbggenerated
     */
    public String getRecord_employee_code() {
        return record_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.record_employee_code
     *
     * @param record_employee_code the value for supplier.record_employee_code
     *
     * @mbggenerated
     */
    public void setRecord_employee_code(String record_employee_code) {
        this.record_employee_code = record_employee_code == null ? null : record_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.record_employee_name
     *
     * @return the value of supplier.record_employee_name
     *
     * @mbggenerated
     */
    public String getRecord_employee_name() {
        return record_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.record_employee_name
     *
     * @param record_employee_name the value for supplier.record_employee_name
     *
     * @mbggenerated
     */
    public void setRecord_employee_name(String record_employee_name) {
        this.record_employee_name = record_employee_name == null ? null : record_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contacts_code
     *
     * @return the value of supplier.contacts_code
     *
     * @mbggenerated
     */
    public String getContacts_code() {
        return contacts_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contacts_code
     *
     * @param contacts_code the value for supplier.contacts_code
     *
     * @mbggenerated
     */
    public void setContacts_code(String contacts_code) {
        this.contacts_code = contacts_code == null ? null : contacts_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.edit_employee_code
     *
     * @return the value of supplier.edit_employee_code
     *
     * @mbggenerated
     */
    public String getEdit_employee_code() {
        return edit_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.edit_employee_code
     *
     * @param edit_employee_code the value for supplier.edit_employee_code
     *
     * @mbggenerated
     */
    public void setEdit_employee_code(String edit_employee_code) {
        this.edit_employee_code = edit_employee_code == null ? null : edit_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.edit_employee_name
     *
     * @return the value of supplier.edit_employee_name
     *
     * @mbggenerated
     */
    public String getEdit_employee_name() {
        return edit_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.edit_employee_name
     *
     * @param edit_employee_name the value for supplier.edit_employee_name
     *
     * @mbggenerated
     */
    public void setEdit_employee_name(String edit_employee_name) {
        this.edit_employee_name = edit_employee_name == null ? null : edit_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.edit_date
     *
     * @return the value of supplier.edit_date
     *
     * @mbggenerated
     */
    public Date getEdit_date() {
        return edit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.edit_date
     *
     * @param edit_date the value for supplier.edit_date
     *
     * @mbggenerated
     */
    public void setEdit_date(Date edit_date) {
        this.edit_date = edit_date;
    }
}