package com.xinshan.model;

public class SysAppButton {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_app_button.sys_app_button_id
     *
     * @mbggenerated
     */
    private Integer sys_app_button_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_app_button.app_id
     *
     * @mbggenerated
     */
    private Integer app_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_app_button.button_title
     *
     * @mbggenerated
     */
    private String button_title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_app_button.button_status
     *
     * @mbggenerated
     */
    private Integer button_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_app_button.only_admin
     *
     * @mbggenerated
     */
    private Integer only_admin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_app_button.alias
     *
     * @mbggenerated
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_app_button.button_name
     *
     * @mbggenerated
     */
    private String button_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app_button.sys_app_button_id
     *
     * @return the value of sys_app_button.sys_app_button_id
     *
     * @mbggenerated
     */
    public Integer getSys_app_button_id() {
        return sys_app_button_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app_button.sys_app_button_id
     *
     * @param sys_app_button_id the value for sys_app_button.sys_app_button_id
     *
     * @mbggenerated
     */
    public void setSys_app_button_id(Integer sys_app_button_id) {
        this.sys_app_button_id = sys_app_button_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app_button.app_id
     *
     * @return the value of sys_app_button.app_id
     *
     * @mbggenerated
     */
    public Integer getApp_id() {
        return app_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app_button.app_id
     *
     * @param app_id the value for sys_app_button.app_id
     *
     * @mbggenerated
     */
    public void setApp_id(Integer app_id) {
        this.app_id = app_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app_button.button_title
     *
     * @return the value of sys_app_button.button_title
     *
     * @mbggenerated
     */
    public String getButton_title() {
        return button_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app_button.button_title
     *
     * @param button_title the value for sys_app_button.button_title
     *
     * @mbggenerated
     */
    public void setButton_title(String button_title) {
        this.button_title = button_title == null ? null : button_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app_button.button_status
     *
     * @return the value of sys_app_button.button_status
     *
     * @mbggenerated
     */
    public Integer getButton_status() {
        return button_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app_button.button_status
     *
     * @param button_status the value for sys_app_button.button_status
     *
     * @mbggenerated
     */
    public void setButton_status(Integer button_status) {
        this.button_status = button_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app_button.only_admin
     *
     * @return the value of sys_app_button.only_admin
     *
     * @mbggenerated
     */
    public Integer getOnly_admin() {
        return only_admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app_button.only_admin
     *
     * @param only_admin the value for sys_app_button.only_admin
     *
     * @mbggenerated
     */
    public void setOnly_admin(Integer only_admin) {
        this.only_admin = only_admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app_button.alias
     *
     * @return the value of sys_app_button.alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app_button.alias
     *
     * @param alias the value for sys_app_button.alias
     *
     * @mbggenerated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app_button.button_name
     *
     * @return the value of sys_app_button.button_name
     *
     * @mbggenerated
     */
    public String getButton_name() {
        return button_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app_button.button_name
     *
     * @param button_name the value for sys_app_button.button_name
     *
     * @mbggenerated
     */
    public void setButton_name(String button_name) {
        this.button_name = button_name == null ? null : button_name.trim();
    }
}