package com.xinshan.model;

import java.util.Date;

public class UserRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.user_record_id
     *
     * @mbggenerated
     */
    private Integer user_record_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.user_id
     *
     * @mbggenerated
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.user_source_id
     *
     * @mbggenerated
     */
    private Integer user_source_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.user_status_id
     *
     * @mbggenerated
     */
    private Integer user_status_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.user_stage_id
     *
     * @mbggenerated
     */
    private Integer user_stage_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.record_date
     *
     * @mbggenerated
     */
    private Date record_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.visit_date
     *
     * @mbggenerated
     */
    private Date visit_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.record_employee_code
     *
     * @mbggenerated
     */
    private String record_employee_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.record_employee_name
     *
     * @mbggenerated
     */
    private String record_employee_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.user_record_id
     *
     * @return the value of user_record.user_record_id
     *
     * @mbggenerated
     */
    public Integer getUser_record_id() {
        return user_record_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.user_record_id
     *
     * @param user_record_id the value for user_record.user_record_id
     *
     * @mbggenerated
     */
    public void setUser_record_id(Integer user_record_id) {
        this.user_record_id = user_record_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.user_id
     *
     * @return the value of user_record.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.user_id
     *
     * @param user_id the value for user_record.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.user_source_id
     *
     * @return the value of user_record.user_source_id
     *
     * @mbggenerated
     */
    public Integer getUser_source_id() {
        return user_source_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.user_source_id
     *
     * @param user_source_id the value for user_record.user_source_id
     *
     * @mbggenerated
     */
    public void setUser_source_id(Integer user_source_id) {
        this.user_source_id = user_source_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.user_status_id
     *
     * @return the value of user_record.user_status_id
     *
     * @mbggenerated
     */
    public Integer getUser_status_id() {
        return user_status_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.user_status_id
     *
     * @param user_status_id the value for user_record.user_status_id
     *
     * @mbggenerated
     */
    public void setUser_status_id(Integer user_status_id) {
        this.user_status_id = user_status_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.user_stage_id
     *
     * @return the value of user_record.user_stage_id
     *
     * @mbggenerated
     */
    public Integer getUser_stage_id() {
        return user_stage_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.user_stage_id
     *
     * @param user_stage_id the value for user_record.user_stage_id
     *
     * @mbggenerated
     */
    public void setUser_stage_id(Integer user_stage_id) {
        this.user_stage_id = user_stage_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.record_date
     *
     * @return the value of user_record.record_date
     *
     * @mbggenerated
     */
    public Date getRecord_date() {
        return record_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.record_date
     *
     * @param record_date the value for user_record.record_date
     *
     * @mbggenerated
     */
    public void setRecord_date(Date record_date) {
        this.record_date = record_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.visit_date
     *
     * @return the value of user_record.visit_date
     *
     * @mbggenerated
     */
    public Date getVisit_date() {
        return visit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.visit_date
     *
     * @param visit_date the value for user_record.visit_date
     *
     * @mbggenerated
     */
    public void setVisit_date(Date visit_date) {
        this.visit_date = visit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.record_employee_code
     *
     * @return the value of user_record.record_employee_code
     *
     * @mbggenerated
     */
    public String getRecord_employee_code() {
        return record_employee_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.record_employee_code
     *
     * @param record_employee_code the value for user_record.record_employee_code
     *
     * @mbggenerated
     */
    public void setRecord_employee_code(String record_employee_code) {
        this.record_employee_code = record_employee_code == null ? null : record_employee_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.record_employee_name
     *
     * @return the value of user_record.record_employee_name
     *
     * @mbggenerated
     */
    public String getRecord_employee_name() {
        return record_employee_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.record_employee_name
     *
     * @param record_employee_name the value for user_record.record_employee_name
     *
     * @mbggenerated
     */
    public void setRecord_employee_name(String record_employee_name) {
        this.record_employee_name = record_employee_name == null ? null : record_employee_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.remark
     *
     * @return the value of user_record.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.remark
     *
     * @param remark the value for user_record.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}